### ISSUE TITLE
Overview figure for methods manuscript

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#1026]
I attempted to sketch an overview figure to summarize some of the automation in this project and how GitHub is used.  It's pretty complex.  That makes it hard to draw an accurate and simple figure but also makes such a figure valuable to readers.

Here's my first draft:
![COVID-19 methods overview v1](https://user-images.githubusercontent.com/3532898/132072909-ba12b83a-4248-45f7-8aea-fc5889a05544.png)

It's in Google Drawings so I can give others access if they want to play around with it.  @rando2 does this make sense?  Do we want to add an overview figure?

_Edit:_ One aspect that is confusing in this version is that "Files" and "Outputs" are separate columns.  In reality, many of the files tracked on these branches are outputs from a GitHub Actions workflow that are committed to the branch.

**Comment by rando2** [comment]
Hey @agitter, I really like this illustration and I think it's a fantastic idea to have a summary figure! 

Looking at it, I'm curious if you think that it might make sense to have either two figures or a two part figure, with one being the table component of what you posted and the second being something like this (very rough) sketch?
![Attachment-1](https://user-images.githubusercontent.com/8975841/132410976-928048f0-9ab7-42c5-b8f3-fa99b23a118d.jpeg)

**Comment by agitter** [comment]
@rando2 I like that layout.  The tabular style I started with was too rigid and not accurately capturing content that is updated by Manubot or a workflow and tracked in GitHub.  Maybe adding cyclic arrows to your version would help convey that idea.

One piece both of our rough drafts is still missing is the idea that contributors are using pull requests to review and modify the main content.  Maybe that is a separate panel?

Should we tag some of the other methods manuscript co-authors for feedback or do you have other suggestions first?

**Comment by rando2** [comment]
@agitter Good point! Again very rough, but maybe something like this? 
![Screen Shot 2021-09-08 at 4 49 24 PM](https://user-images.githubusercontent.com/8975841/132583644-48359aca-5b99-4029-8edc-9045aa9b50ff.png)

**Comment by agitter** [comment]
Yes, that's the part of the workflow I had in mind.  This would be a lot easier to iterate on with a whiteboard, but I'll attempt to give some comments.

On the left, perhaps not all issues should feed into the synthesized analysis.  The idea would be that a couple issues centered around one topic (e.g. HCQ) have arrows into "Synthesized HCQ Analysis" and others on different topics do not.  That Analysis box would still have other inputs as you show now, possibly moving the preprints or publications without corresponding issues closer to the box.  We don't necessarily need to differentiate too heavily between preprint versus peer reviewed versus MERS/SARS papers when illustrating prior literature.  I think the main point is that we're interpreting the new papers being added through the pull request in the context of related work.

In the Manubot paper we already had [this image](https://github.com/greenelab/meta-review/blob/master/content/images/workflow.png) detailing the pull request workflow, so we don't need to go into detail there.

**Comment by rando2** [comment]
Thanks @agitter! Would it make sense for me to add onto your Google Slides to try to get the three panels set up? The Manubot figure is great!

**Comment by agitter** [comment]
I invited your .edu email to the Google Drawing.  I can message you a link if that doesn't work.

**Comment by rando2** [comment]
Got it! Thank you!

**Comment by agitter** [comment]
@rando2 I tried to merge the ideas in my tabular overview image with your "data flow" oriented version.  What do you think of this:

![COVID-19 methods overview v3](https://user-images.githubusercontent.com/3532898/132960520-48af7b82-0ba2-4613-8e22-ed7241eae01d.png)

Anyone can comment on the drawing at https://docs.google.com/drawings/d/1krx92jwzu-JEsRYyr7kDptbB_H7Xm-9eYBfJUT2EpSY/edit?usp=sharing and I can give edit permission to whoever would like it.

I can work on the text size and alignment once we finalize the overall layout.

**Comment by agitter** [comment]
@cgreene and @vincerubinetti do you have any thoughts about this latest draft of the new workflow overview for the DISCO 2021 COVID-19 methods manuscript?

**Comment by vincerubinetti** [comment]
I don't have any comments about the workflow itself. Looks inline to what I understand your setup to be.

I could help streamline the figure, or if we don't have time or you otherwise don't want me messing with it, I can write some specific comments on the sketch in google.

**Comment by cgreene** [comment]
I think this makes a lot of sense. What do you think about adding scite to the reference metadata? That's the only comment that I have.

**Comment by agitter** [comment]
> What do you think about adding scite to the reference metadata?

Yes, that's a good idea.

> I could help streamline the figure,

@vincerubinetti if you have time to work on this, I would be grateful for the help.  You have _much_ better design skills than me.  My current todo list of modifications is:
- Add scite to the reference metadata area
- Increate the 12 point font size
- Update the HTML manuscript screenshot from https://greenelab.github.io/covid19-review/ and make it higher resolution
- Move some boxes to better use whitespace
- Rescale the green database objects to make the ovals at the top similar in height

I'll invite you to the Google Drawings.  You could also export from there and work locally if that is easier.  Note that the Manubot logo is originally from the manubot/resources repository, but I had to convert the svg to png before I could import it into Google Drawings.

**Comment by vincerubinetti** [comment]
How about this 
https://lucid.app/lucidchart/invitations/accept/inv_316c0a66-c2c2-4cc4-90c7-ca62f2ac2e5a?viewport_loc=-683%2C472%2C2758%2C1324%2C0_0

![covid 19 review workflow figure (1)](https://user-images.githubusercontent.com/8326331/133145075-66a86243-6862-4811-a59a-de2109c5f567.png)

**Comment by agitter** [comment]
That's amazing @vincerubinetti.  I really like it.

A few minor formatting suggestions:
- Make "sources" lower case in the "Data Sources" section and possibly "repository" in "GitHub Repository". It looks like we're mostly using sentence case.
- Add "scite" (lower case) as another box in the "Reference metadata" section
- Make "metadata" lower case in "Author Metadata" in the master branch
- Change "GitHub action" to "GitHub Actions" in the legend

Do you think this should be full page width or column width in the manuscript?  It's a two-column manuscript format.  We're tight on space, but this is arguably the most important figure so I want it to be clear.

**Comment by vincerubinetti** [comment]
How's this. Once you guys approve, I'll zip up the exported PNG and SVG versions and attach them here as final. 

Anyone should also be able to use that Lucid link to edit it, though you might have to create a Lucid account.

![covid 19 review workflow figure](https://user-images.githubusercontent.com/8326331/133157415-a3ed5649-6c22-4a21-a319-5cd465ec7a4a.png)

**Comment by agitter** [comment]
This version looks great to me.  Thanks for the updates.

What does the star icon indicate?  I'll write the figure caption and want to say something about that.

@rando2 any comments before we add it?

This is A4 print.  We'll aim to make it full line width and cut elsewhere if needed.

**Comment by vincerubinetti** [comment]
I just put a star there to give it extra visual pop since it's the master branch and where the "main content" lives. Other ideas how to do that besides a star are welcome; that's just what I came up with.

Not something I felt needed an entry in the legend, just wanted to draw attention to it.

**Comment by rando2** [comment]
This is gorgeous @vincerubinetti!!! 

Other than the star, my only comment would be that I don't think the contribution instructions need to be listed there (since they don't get incorporated into the manuscript, so they're not really part of the "flow"). But maybe we do want them listed, since we discuss them in the text. I don't feel super strongly either way!

**Comment by vincerubinetti** [comment]
I agree Halie, I was wondering about that. I've removed the contribution bullet.

How about if i do the star this way. Maybe it looks less like a precise meaning and more like just a highlight:

![image](https://user-images.githubusercontent.com/8326331/133159006-2fc10d88-769f-4493-bd4d-b2689fb1a195.png)

**Comment by rando2** [comment]
I like it @vincerubinetti! We can also just mention in the legend that we have it starred because it's the branch that everyone interacts with other than like, the three of us and Michael.

**Comment by vincerubinetti** [comment]
> We can also just mention in the legend

Maybe the caption? If not, how to say it in a pithy way like the rest of the legend entries.

**Comment by rando2** [comment]
Sorry, I meant caption! So I agree!

**Comment by agitter** [comment]
That star placement and significance look good to me.  I can write the caption and will describe the star accordingly.

I'm okay removing the contribution instructions from the master branch box.

@vincerubinetti you could open a pull request to add the pdf and svg of this version to `content/images`.  Or if you add them here, I'll do it.  Thanks for the fantastic graphic.

**Comment by vincerubinetti** [comment]
It'd be helpful for you to do it so I can focus on the other pr, and so you can add the caption and figure ref itself.

Here's the final:

[workflow-figure.zip](https://github.com/greenelab/covid19-review/files/7157551/workflow-figure.zip)

**Comment by agitter** [comment]
@vincerubinetti the dimensions of the workflow figure make it hard to fit into the PDF page limit.  Do you think it would look okay to move the legend to the top right and the manuscript screenshot to the right of the gray GitHub repository box?  Then the figure could be full page width and shorter.

**Comment by vincerubinetti** [comment]
Here you go. If this is fit to page width, the text might be too small and illegible though.

[covid 19 review workflow figure horizontal.zip](https://github.com/greenelab/covid19-review/files/7165592/covid.19.review.workflow.figure.horizontal.zip)

**Comment by agitter** [comment]
Thanks a lot @vincerubinetti .  The text is a little small, but at 100% zoom I think it is still readable.  It does take up much less space.

I was already rescaling the width of the original orientation to 65% of the text width so it wouldn't take up a whole page.  Here is a PDF with both versions:
[covid19_review_methods_disco21_camera_ready.pdf](https://github.com/greenelab/covid19-review/files/7166332/covid19_review_methods_disco21_camera_ready.pdf)

Do you think the horizontal orientation works?

**Comment by vincerubinetti** [comment]
Ah okay, the context makes it clearer why you wanted a horizontal version. I think its fine. The text in the figure isnt that much smaller than the paper text.

**Comment by agitter** [comment]
Great!  That orientation helped a lot with space.
