### ISSUE TITLE
Steps for submission of Diagnostics manuscript

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#1094]
Since there hasn't been much movement on the diagnostics manuscript in a bit, right now I am trying to get it organized enough to submit.

I wanted to check in and see if there is currently any outstanding text or To Dos that people were planning to address, since I'm hoping to get a draft out to authors this week.

To dos:

1.  Add a sentence about type III CRISPR (needs review, #1093)
2.  Reorganize/streamline existing text (#1091, #1092 and #1093)
3.  Look through open issues to see if there are any critical papers we need to add (suggestions also welcome)
4.  Assign author order and update metadata
5.  Generate docx and email out for review

Tagging the authors I identified in my preliminary scan of the git log: @cbrueffer @RLordan @aadattoli @nilswellhausen @jessegmeyerlab @davidmanheim @davemai @aimundo @SystemsResearch @SiminaB @cgreene @agitter

Also, now is a great time to double-check the [author metadata](https://github.com/greenelab/covid19-review/blob/master/content/metadata.yaml) and make sure your details (emails, affiliations, conflicts of interest) are correct!

**Comment by RLordan** [comment]
Do we want to have a paragraph on the role of testing in the pandemic? How the use of PCR vs Antigen has evolved perhaps? referring to this storyline in particular doi:10.1056/NEJMp2025631

**Comment by rando2** [comment]
@RLordan and @aimundo both of those sounds like excellent topics to cover!

**Comment by aimundo** [comment]
@rando2 how does linking news articles work with Manubot? I think for those last paragraphs I will work on I will mainly rely on those type of sources, but I am unsure how citing those would work.

**Comment by rando2** [comment]
@aimundo you can do it like this: \[@url:https://www.livescience.com/coronavirus-tests-available.html] -- just let me know if you have any issues!

**Comment by aimundo** [comment]
@rando2 I added my contribution to the Diagnostics manuscript, I hope I did it the right way. If there's anything I need to change please let me know.

**Comment by rando2** [comment]
@aimundo I can see the changes you made but there isn't an open PR! Could you try going here: [https://github.com/greenelab/covid19-review/compare/master...aimundo:master](https://github.com/greenelab/covid19-review/compare/master...aimundo:master)

And see if you can open a PR that way? I'll review the text ASAP!

**Comment by rando2** [comment]
Yay! I think we're almost there! @RLordan @aimundo, once #1102 and #1091 merge in, are either of you planning to write more text or are we reasonably happy with what we have?

Once all of the outstanding PRs are merged, I'll do a final sweep to clean up spelling, abbreviations, and other minor issues. Then I'll crunch the authorship numbers and send out an email asking for people to review the manuscript! 

If anyone has any concerns they want to see addressed, please let me know!

**Comment by aimundo** [comment]
@rando2, I only need to add @RLordan's suggestion of citing an example of failed testing policies, I'll take a look at the references he provided later tonight and add the additional sentences maybe on Friday morning (sorry, I just defended my dissertation on Monday and I'm working on some minor corrections, juggling through some paperwork and a small amount of celebration). But I expect my final additions to be ready by Friday and once that's done, from my side everything would be good to go.

**Comment by RLordan** [comment]
Congratulation @aimundo on defending! 

and for @rando2 & @aimundo - 
Just so that we aren't overlapping, I was thinking of adding a few sentences on the Michael Mina story of LFTs and choosing whether PCR or LFTs can give an indication of infectiousness. Do you want me to do that, or have you already started? If nobody plans on writing that, I can do it tomorrow.

**Comment by rando2** [comment]
Congratulations Dr. @aimundo! How exciting!!!!! Thank you for working on this during such an intense week!!!

@RLordan I'll also keep an eye out for your PR! I had flagged a possible spot to cover that topic (see picture) -- but please feel free to do whatever makes the most sense!

![](https://user-images.githubusercontent.com/8975841/159926345-447f8c20-8099-46e3-99aa-5b4e78da432f.png)

**Comment by rando2** [comment]
Hi everyone! I think we're almost there! 
Here is the information about authorship. I opened #1111 to edit the metadata file but here's the rationale.

[gitlog.10.diagnostics.csv](https://github.com/greenelab/covid19-review/files/8383291/gitlog.10.diagnostics.csv) is a csv file with all of the commit history from the log is attached (this is one of the only manuscripts that has been contained in a single file throughout the whole project!)

Here are some summary statistics I got from that file and looking at the various PRs associated with this manuscript:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/halierando/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/halierando/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Person | Order | Notes | # Lines | Writing- Original Draft | Writing - Review & Editing | Project Administration
-- | -- | -- | -- | -- | -- | --
@rando2 | 1 |   | 2745 | x | x | x
@RLordan  | 2 |   | 209 | x | x | x
@cbrueffer  | 2 |   | 189 | x | x | x
@aadattoli  | 3 |   | 274 | x |   |  
@jessegmeyerlab  | 3 |   | 178 | x | x |  
@davidmanheim | 3 |   | 177 | x | x |  
@SystemsResearch | 4 |   | 75 | x |   |  
@aimundo  | 4 |   | 69 | x | x |  
@davemai | 5 |   | 23 | x | x |  
@nilswellhausen  | 6 |   |   |   | x |  
@agitter  | 8 |   | 4 |   |   | x
@cgreene | 9 |   | 44 |   |   | x
Yael | Ack | Ack | 17 |   |   |  
@SiminaB  | Ack | Ack | 11 |   |   |  
@LucyMcGowan  | Ack | Ack | 2 |   |   |  
@gregszetoAI  | Ack | Ack | 1 |   |   |  



</body>

</html>

If anyone has suggestions or feedback (especially on whether I accurately captured your contributions), they are welcome! I'm hoping to get a Word version out by email for approval in the next day or two.

**Comment by rando2** [comment]
Add @joshuablake to acknowledgements!

**Comment by agitter** [comment]
I'm still planning to make a pull request with any final proofreading edits.  I'll aim to do it in the next couple days.

**Comment by rando2** [comment]
Once I get in touch with @SystemsResearch for approval and merge #1132, #1134 and #1135 (just pending manubot builds), I think it will be time for me to do one final read through and start moving forward on posting a preprint! 

If anyone was planning to open any other PRs for this one, please let me know!

**Comment by agitter** [comment]
Closed by https://arxiv.org/abs/2204.12598.  Great work everyone!

**Comment by aimundo** [comment]
Done! I opened the PR, let me know if it worked.

**Comment by rando2** [comment]
@agitter I think this was some sort of email lag -- I checked and there was a PR (#1108) opened by @aimundo around when that message seems to have originated (there was more detail in the version that came to my email suggesting it was probably written around March 22nd)! But, this is a nice opportunity to say this is high on my to do list and I will be in touch soon with PRs addressing the feedback we got on this manuscript.
