### ISSUE TITLE
Bug: formatting issue in @url citations with trailing /

### ISSUE THREAD

**Issue by cbrueffer** [greenelab/covid19-review#1131]
Unsure if this is the best place to report, it's probably a Manubot issue: `@url` citations with a trailing `/` in the URL are incorrectly formatted. Here's an example from the Diagnostics manuscript where the following citation results in formatting in the screenshot below:

`[@url:https://www.opb.org/article/2022/03/02/oregon-schools-guidance-mask-mandate-end/; @url:https://www.wptv.com/news/education/palm-beach-county-public-schools-to-stop-covid-19-contact-tracing]`

![Screenshot_2022-04-14_23-26-06](https://user-images.githubusercontent.com/2705287/163479696-609fcaea-9635-4e09-a328-eec0faae18aa.png)

**Comment by rando2** [comment]
@cbrueffer Yep, that's just manubot disliking trailing slashes! I wrote some code to remove them but clearly missed some cases. I will fix this case before finalizing the preprint text! Thank you for letting me know.
