### ISSUE TITLE
Need to appeal arXiv rejection of the novel vaccines manuscript

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#1175]
The reason for the rejection is: "Our moderators have determined that your submission is on a topic not covered by arXiv or that the intended audience for your work is not a community we currently serve."

Obviously, this is weird. Here is the draft of the appeal I am writing. I'd love any input from other authors. I'll meet with Casey at 2pm MT on Friday to discuss and submit it.

Draft:  
I am writing to appeal the recent MOD-17330 decision on the manuscript submitted as submit/4485831. The paper summarizes and contextualizes recent advances in DNA and mRNA vaccine technologies. This work is the latest manuscript written by the COVID-19 Review Consortium, which is a large open-publishing effort by 50+ scientists from a variety of fields to synthesize and consolidate the COVID-19 literature. To date, this consortium has preprinted six articles with arXiv. One (arXiv:2109.08633) describes the technical processes underlying the project and was published at a workshop for JCDL 2021. The five remaining preprints, as well as the rejected submission, are the literature review products produced by the Consortium. Three of them are now published in the journal _mSystems_ (arXiv: 2102.01521; 2103.02723; 2102.02250), with a fourth in revision (arXiv:2204.12598). The final preprint (arXiv:2208.08907) is the companion manuscript to the rejected submission.

Together, these two articles provide a comprehensive discussion of the evolution of vaccine development. In arXiv:2208.08907, we review vaccine technologies based on whole viruses and their constituent pieces. We describe how they were developed in prior pandemics and how they have been applied to SARS-CoV-2 worldwide. In submit/4485831, we move to the 1980s and beyond to describe the developments underlying vaccine technologies that introduce the DNA or mRNA code for a viral antigen for expression in the host. This manuscript follows similar formatting and addresses similar topics to its companion, but the content is unique.

The reason indicated for the moderation decision was that the "submission is on a topic not covered by arXiv or that the intended audience for your work is not a community we currently serve." However, this does not seem consistent with other moderation decisions made by arXiv. Notably, the companion manuscript (arXiv:2208.08907) was recently submitted and approved. Additionally, arXiv serves the field of quantitative biology, with moderators and advisory committee members with expertise in molecular biology, bioinformatics, and omics, which are the scientific fields upon which advances in nucleic acid vaccines are based and which are the focus of the rejected article. Furthermore, arXiv preprints include a large number of papers related to COVID-19 vaccines **(e.g.,** [**arXiv:2112.10500**](https://arxiv.org/abs/2112.10500)**)**; our article describing the underlying molecular biology of the nucleic acid technology used to induce adaptive immunity would seem to be as well-suited to quantitative biology as any of these. Based on our detailed investigation of these other articles, however, we would like to suggest q-bio.OT as an alternative subject area for the submission (we had originally submitted it under q-bio.BM).

**This manuscript also showcases new advances we have made in integrating code with text to create truly living manuscripts. For this manuscript, data were automatically downloaded from several online sources and processed to provide up-to-date information rendered in this manuscript as tables, figures, and in-line statistics. This fully open approach to publishing, where the code used to conduct the analyses discussed in the manuscript is publicly available and automatically connected to the text, is an important step towards scientific reproducibility. Therefore, the approach we took to writing this review is also relevant to the members of the quantitative biology community.**

arXiv is an integral piece of the COVID-19 Review Consortium's strategy to use open publishing to combat misinformation during these challenging times. We appreciate your consideration of our appeal.

**Comment by RLordan** [comment]
Hey @rando2 … that decision baffles me… 

nothing to add really, the response is reasonable to me and well written. You could  include an example of a similar paper they accepted outside our group as another example of you so wish but it isn’t necessary. Very unusual.

**Comment by agitter** [comment]
That's surprising and disappointing.  I'm optimistic about the appeal.

My advice is to focus on 1) all the precedent set by our prior accepted preprints (especially the recent traditional vaccines paper) and 2) the automation that makes this unique and relevant for the arXiv audience.  1) is very well covered already.  You could add a sentence or two about 2).

**Comment by rando2** [comment]
Thank you both! I made changes (in bold) based on your suggestions.

**Comment by RLordan** [comment]
> Thank you both! I made changes (in bold) based on your suggestions.

Thanks Halie, reads very well. Fingers crossed

**Comment by agitter** [comment]
Looks good to me

**Comment by agitter** [comment]
@rando2 any updates on the appeal? Did the moderators make a decision one way or the other?

**Comment by rando2** [comment]
@agitter No update yet! I submitted everything to _mSystems_ this week without the preprint, since it seemed better to move on it than wait for the vaccines world to change again. I still need to update #1176

**Comment by agitter** [comment]
Good decision to go ahead and submit to the journal.

**Comment by rando2** [comment]
@RLordan No news!!! I actually checked yesterday to see if there was any movement, and then immediately after being disappointed heard the good news from the journal!

**Comment by RLordan** [comment]
@rando2 no worries, yes the journal was a pleasant review. Let me know if you want help with anything.

**Comment by agitter** [comment]
Should we start to consider a backup plan?  Now that this has been resubmitted and the revisions were minor, it could be accepted at the journal fairly quickly.

https://arxiv.org/help/moderation/appeals notes
> Most appeals are resolved within a two week period, but some may take longer. If you have not heard from arXiv within two weeks of receiving the notification that your appeal has been received, please feel free to reach out to us for a status update through the appropriate contact channel, moderation@arxiv.org.

I don't want to hassle the moderators, who are academics volunteering their time.  However, one idea would be to politely ask if they are close to a decision.  If they are not, we could withdraw from arXiv and preprint elsewhere before the journal publication appears.

If it comes to that, after skimming https://asapbio.org/preprint-servers OSF Preprints looks most appealing.  I haven't used it though so I would be open to other suggestions.

**Comment by RLordan** [comment]
I think a back up plan is fair. Considering the comments, I would expect a quick decision. I don't think there is any harm in asking politely if a decision is close.

**Comment by cbrueffer** [comment]
Is it worth pre-printing at all given that mSystems is open-access? I guess the ability to update preprints more rapidly is appealing, but at this point I wonder how likely that is.

**Comment by rando2** [comment]
OK, the paper is formally accepted now! I will update the ticket. We may want to send an email before jumping ship completely.

**Comment by agitter** [comment]
@cbrueffer it's a good point.  The benefits are minor now that the paper has been accepted and the journal is open access.  Possible reasons to still preprint are:
- @cgreene and I preprint (almost) everything our labs write as a policy/habit.
- Share the snapshot of the manuscript quickly while it is all up to date. The pathogenesis manuscript took almost exactly a month from acceptance to posting at the journal website.
- With arXiv we have the ability to push updates for smaller changes that don't require a formal journal correction or a major peer-reviewed next version journal submission.
- Consistency across the COVID-19 project.

@rando2 please do send the polite email and let us know if you hear back.

**Comment by rando2** [comment]
Hi all, I just heard back! It seems like I made a mistake on the initial submission. They let me fix it now, so fingers crossed that we will be approved! I'm so sorry about this, I will triple-check future submissions.

**Comment by agitter** [comment]
Closed by https://arxiv.org/abs/2210.07247  Thanks for getting this posted @rando2.

For the sake of tagging different versions, which version of the manuscript did you submit to arXiv?

**Comment by rando2** [comment]
@agitter I sent them the version in #1182 because I thought that would make things easier!

**Comment by agitter** [comment]
@rando2 the arXiv metadata has the consortium author in a different order than the preprint.  I'm not sure if we can fix that without submitting another version.  Maybe that is only worth doing if we want to send v2 to arXiv?

**Comment by rando2** [comment]
@agitter That is really odd, I usually copy it directly out of the docx and it's correct there! It seems like it would require submitting a new version to change it. Presumably there will be a few more changes in the coming weeks during the editorial process, so perhaps it would make the most sense to fix it then?

**Comment by agitter** [comment]
Yes, let's leave it for now.  If we make more small changes during the proofing process, we can submit another version to arXiv with those changes as you suggest.
