### ISSUE TITLE
Revisions to Novel Vaccines manuscript

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#1178]
Handled in #1179:
- [x] 1.3
- [x] 1.4 
- [x] 1.5
- [x] 1.6
- [x] 1.7

Handled in #1180:
- [x] 1.8

### Reviewer 1 (Comments for the Author):

The narrative review by Rando et al. is an account of the history of nucleic acid-based vaccines, with particular focus on Covid-19 vaccines their clinical trials, effectiveness and adverse events. An accompanying review article by the same group , which I did not review, deals with traditional vaccines for Covid-19 and it does not appear to overlap with, or be required for, the article under review
This review is very comprehensive, informative and very well written. The literature consulted is extensive and relevant. 
Minor comments:
3) Line 239 - This reference is not available
4) Line 276 - Malaria is not a bacterial disease
5) Line 683 - 2,686 represents 68% of the participants in the trial
6) Line 266 and 287 - Which immune stimulant molecules? Which two vaccines?
7) The reference list does not follow the format required by mSystems. In particular, volume and page # are missing. 
8) Figure 2 and 3 are of poor quality, with overlapping labels and hard to see shades of grey.

**Comment by rando2** [comment]
Drafting a response:  
  
We thank the reviewer for their kind words and helpful suggestions. We have made the following changes to the manuscript:  
3) Line 239 - This reference is not available

This work in progress is currently hosted on the GitHub pages rendering of the broader COVID-19 Review Consortium project. However, we suspect many readers may encounter a lag when accessing the bookmarked link due to the large amount of material on this page. \[Whatever our solution is\]  
  
4) Line 276 - Malaria is not a bacterial disease  
5) Line 683 - 2,686 represents 68% of the participants in the trial  
6) Line 266 and 287 - Which immune stimulant molecules? Which two vaccines?  
7) The reference list does not follow the format required by mSystems. In particular, volume and page # are missing.  
  
The change has been made.  
  
8) Figure 2 and 3 are of poor quality, with overlapping labels and hard to see shades of grey.

**Comment by RLordan** [comment]
Responses look good to me!

**Comment by rando2** [comment]
Okay, I think I have addressed all the feedback between #1179 and #1180! Please let me know if you have any suggestions!

**Comment by rando2** [comment]
This was resubmitted yesterday!
