### ISSUE TITLE
Enable AppVeyor artifact comments in pull requests

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#119]
**Is your feature request related to a problem? Please describe.**
Viewing manuscript artifacts through GitHub Actions is somewhat cumbersome.

**Describe the solution you'd like**
AppVeyor can comment on a pull request after the manuscript builds, directly linking to the HTML and PDF artifacts.  See https://github.com/greenelab/deep-review/pull/997#issuecomment-595857858 for an example.

**Describe alternatives you've considered**
I attempted to implement a similar feature with GitHub Actions comments upstream in rootstock.  It isn't currently possible for reasons detailed in https://github.com/manubot/rootstock/pull/327

**Additional context**
The project leads would need to evaluate the tradeoffs of having manuscript artifacts more easily accessible during review versus the additional notifications generated.  AppVeyor's pull request comments trigger a notification every time the artifact is posted.  I don't mind that, but some people do.

**Comment by rando2** [comment]
Hi @agitter , sorry for my slow response on this issue. For this project especially, I think user-friendliness is a priority, even if it generates more notifications. If this is something you are able to implement, I think it would be helpful for this project and potentially might serve to pique more people's interest in manubot.

**Comment by agitter** [comment]
The `.appveyor.yml` config file is already in the repository.  Someone from @greenelab with the appropriate credentials should be able to enable AppVeyor builds by following the rootstock [setup instructions](https://github.com/manubot/rootstock/blob/master/SETUP.md#previewing-pull-request-builds-with-appveyor)
> You can optionally enable AppVeyor continuous integration to view pull request builds. Unlike Travis CI, AppVeyor supports storing manuscripts generated during pull request builds as artifacts. These can be previewed to facilitate pull request review and ensure formatting and reference changes render as expected. When a pull request build runs successfully, @AppVeyorBot will comment on the pull request with a download link to the manuscript PDF.

> To enable AppVeyor, follow steps 1 and 2 of the [AppVeyor welcome](https://www.appveyor.com/docs/) to sign in to AppVeyor and add your manuscript repository as an AppVeyor project. The repository already contains an .appveyor.yml build configuration file, so no other setup is required. AppVeyor only runs when it detects changes that are likely to affect the manuscript.

**Comment by cgreene** [comment]
I think I have done this.

**Comment by agitter** [comment]
Thanks @cgreene. It worked in #122.
