### ISSUE TITLE
"Commit" not recognized in build.sh

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#1203]
We have been seeing Manubot fail frequently with a keyerror because of 'commit' here:

> \# Log the external-resources commit used when building the manuscript
EXTERNAL_RESOURCES_COMMIT=$(curl -sS https://api.github.com/repos/greenelab/covid19-review/branches/external-resources | python -c "import sys, json; print(json.load(sys.stdin)['commit']['sha'])")
echo >&2 "Using external-resources commit $EXTERNAL_RESOURCES_COMMIT"

I'm guessing this means that the curl command is returning something that either a) isn't a dictionary, or b) doesn't contain a key named `commit`. I tried to replicate on the command line and rand it about 20 times without it failing. I'm making this issue as a place to stash ideas for how to troubleshoot or fish this!

**Comment by rando2** [comment]
![](https://user-images.githubusercontent.com/8975841/214147133-3822ce31-30be-43e2-be83-c0f0a377abb3.png)

**Comment by agitter** [comment]
Maybe the next thing to do would be to make this line a tiny separate python script that we call so it can have some reasonable error handling and tell us what it gets back from curl when the response is unexpected.

**Comment by rando2** [comment]
I will finalize this tomorrow -- much cleverer approach than piping a bunch, which is what I was originally doing!
