### ISSUE TITLE
Permissions & writing to master

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#154]
We seem to have found a bug with GitHub where users who have been invited to a role in the repository but have not yet accepted can push to master, regardless of what permissions they were invited with. In this particular case, we had writes to master from someone who had a pending invitation for read permissions!

I've sent an inquiry to GitHub, but in the meantime, @ypar and I were trying to tighten things up to try to prevent this. (In the documentation, I specifically emphasized that we have it set up so that newbies don't have to worry about writing by mistake-- turns out, that's not true!!!) 

I'm attaching what we now have the branch protection rules set to for master:
![Screen Shot 2020-04-06 at 4 44 07 PM](https://user-images.githubusercontent.com/8975841/78604475-dc1a7300-7827-11ea-9c09-958fcf399d58.png)

@rdvelazquez said: "if you are looking at not allowing pushing to master you will likely want to make master a "projected branch" and then not allow anyone to push to it. This may be a helpful thread: isaacs/github#1390 "

I just wanted to get everyone in the same place and see if there are any thoughts on what would be the best approach, especially given the CI we currently have implemented and are hoping to implement (e.g. #144 ). I am new to CI and don't have a great read on this!

I'll update when I hear back from GitHub, as well.

@agitter @rdvelazquez @ypar @cgreene

**Comment by agitter** [comment]
Those settings make sense to me.  We do want an approval and the GitHub Actions workflow to pass before merging to master.  The AppVeyor status checks don't matter.

**Comment by rdvelazquez** [comment]
The settings look good to me.

**Comment by cbrueffer** [comment]
Looks reasonable to me as well.

**Comment by rando2** [comment]
Thanks everyone! I'll close this issue for now, but happy to revisit if we need to allow better permissions for bots down the line!
