### ISSUE TITLE
Underexplored Therapeutics

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#155]
What do you think about adding a section -- either as part of the summary, or before/after it, like "Summary and Further Avenues" or something -- talking about what future research regarding hydroxychloroquine and its derivatives could/should explore? (Unless there is a section elsewhere on this?)

I found this medicinal chemistry paper on hydroxychloroquine alternatives (hydroxyferroquine derivatives, which are organometallic agents) that showed selectivity against SARS-CoV back in 2006. Links here:
https://www.ncbi.nlm.nih.gov/pubmed/16640347
https://pubs.acs.org/doi/full/10.1021/jm0601856#

A section on further research on these antivirals could summarize:

What information we still need to know about hydroxychloroquine and its effectiveness / what current data are lacking (which you do here already)
Alternatives to hydroxychloroquine as antivirals that might be worth exploring (^ paper above)
Maybe... some notes on how antivirals are developed and where we could go from here? There might be another section on this part, not sure!
Also found this paper on antiviral development, which may or may not be worth citing (but putting it here to remind myself and anyone else interested, to think about):
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4765712/
https://www.elsevier.es/es-revista-medicina-universitaria-304-articulo-history-progress-antiviral-drugs-from-S166557961500037X
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2972676/pdf/main.pdf

_Originally posted by @dianerafi in https://github.com/greenelab/covid19-review/pull/146_

**Comment by rando2** [comment]
@hufengling @nilswellhausen @RLordan @dianerafi @catherinedawn @rbharath @nafisajadavji 

Sorry if I missed anyone, please feel free to tag additional people! This is a great question and I'd love to hear what you all think about working potential under-explored avenues into the outline of the Therapeutics section. I think my default would be to add a new section to the end (after Oligonucleotide Therapies), but definitely open to hearing alternative ideas!

@dianerafi would you be interested in putting together your ideas as a pull request once we figure out where to put it?

**Comment by rbharath** [comment]
There was a very intriguing [paper](https://journals.lww.com/jtrauma/Citation/publishahead/Is_There_a_Role_for_Tissue_Plasminogen_Activator.97967.aspx) proposing that tPA could be used as a treatment for critically ill patients in the absence of a ventilator. I wrote up a brief summary of the paper [here](https://forum.deepchem.io/t/interesting-preprints-papers-on-coronavirus/99/23).

**Comment by dianerafi** [comment]
@rando2 sounds great, I would be happy to get together some ideas and create a pull request as soon as I get the chance. At the end after Oligonucleotide Therapies seems like a logical spot!

**Comment by RLordan** [comment]
Hey @rando2 @dianerafi et al, yes a final summary section would definitely be a good addition to the therapeutics section. I am happy to help on that for sure if anyone required it.

**Comment by nilswellhausen** [comment]
Sounds great! I will try to put together a couple of ideas.
