### ISSUE TITLE
Misleading news reporting about Swedish treatment with chloroquinine

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#160]
I keep seeing that "Swedish hospitals have stopped using chloroquinine to treat COVID-19" which seem to be a story broken in the US by [Newsweek](https://www.newsweek.com/swedish-hospitals-chloroquine-covid-19-side-effects-1496368). It is based on [this article](https://www.expressen.se/nyheter/carl-40-fick-kramp-och-syn-problem-av-coronamedicin/), which I have some serious questions about. My Swedish is a bit rusty, but I think I got most of it (trusting Google translate and Swedish Wikipedia for medical terminology). In case it's helpful to our CQ/HCQ researchers, I'm going to summarize this article below, as well as a better article I found from a different Swedish newspaper

Summary: "Sweden has stopped using hydroxychloroquinine for COVID-19" as US sources have been saying this morning is a very strong way to present this information. Some Swedish hospitals have stopped administering chloroquinine pending results from clinical trials because the side effects are more severe than they expected. They seem particularly worried about the risk for cardiac arrest. @hufengling and collaborators were already on top of this drug having severe side effects.

@cbrueffer is actually in Sweden, so I'll tag him in case he can give any context. For example, Expressen doesn't seem like a particularly reliable news source, but I haven't heard of it before.

Main takeaways:
1. I believe they are talking about CQ, not HCQ, because they call it klorokin and Google says HCQ would be hydroxiklorokin. @hufengling already discusses in #146 that CQ has serious side effects. I will use the spelling "klorokin" below to avoid mistranslating in case this is an ambiguity.
2. The main point of the article that I've seen referenced by US sources is that this one person had known side effects to what was almost certainly too high of a dose, although the dose they report is 4 tablets of unspecified size. 
3. The other article, from Göteborgs-posten, seems much more credible, but refers to decisions made at a few hospitals based on concerns about heart-related side effects. My impression is that the Swedish standard of care is just a little more cautious, and since they are able to save most of their patients without antivirals, are concerned about the side effects, and are skeptical of the French study, they're moving away from chloroquinine pending the results of clinical trials.  

-----------------------------------------------------------------------------
**Summary of Expressen article**

Most of this article is based on the experiences of one patient, Carl Sydenhag, a 40 year old  who tested positive on March 23rd and was treated in Stockholm. He was taking "2 tablets" (no size indicated) of klorokin in the morning and two in the evening and was also receiving antibiotics intravenously, but he started to feel worse instead of better. I think it literally says: "I got cramps and a headache like nothing I had ever previously experienced. It felt like I had stepped into a high voltage power plant." His peripheral vision was also reduced. He read that these are rare side effects (1/100) of taking klorokin. Poison Control and the hospital agreed it was too high of a dose. Today he has recovered but his vision still feels worse than usual and he is still dizzy. But he says it's possible that the "malaria medicine" helped and if so he's very grateful, "men man måste dosera rätt [but one must dose correctly]."

Then they say many hospitals in Sweden had been giving klorokin against COVID-19, but last week the hospitals in Västra Götaland county stopped doing this. They do not include a quote or a reference. They say the Stockholm hospital that prescribed klorokin to Carl Sydenhag has also decided to stop giving malaria medicine to corona patients, according to the [Göteborgs-posten](https://www.gp.se/kultur/kultur/vi-70-plussare-tycks-vara-en-ny-kategori-m%C3%A4nniskor-1.26458244).

Then they quote a letter from Hedvig Glans, who they say is the section chief for the infections unit at the Karolinska University hospital basically saying that they usually give klorokin in the more severe cases and that more research on its efficacy is needed. But it seems like [she's actually a doctoral student](https://news.ki.se/doctoral-student-hedvig-glans-is-one-of-the-experts-in-kis-covid-19-team) (who seems extremely knowledgeable, but that's still kind of a big difference from a reporting standpoint?) She says that its utility for COVID-19 is under review and it is being used less. She also explicitly talks about klorokinfosfat, which would translate to chloroquine phosphate.

------------------------------------------------
**Summary of Göteborgs-posten article**

There is a bit of context at the top about using already-developed drugs to treat COVID-19 and how klorokin is the best known currently because of social media and Trump. Then they say that Swedish doctors have been prescribing klorokin for serious cases. 

Most of the article is quotes and a conversation from Magnus Gisslén, a professor/consulting physician** in the infection clinic from Salgrenska University Hospital East who says that in the beginning, they were giving klorokin like everyone else because there were some "provrörsstudier" (Google says literally "test tube studies" so likely _in vitro_ studies) that showed it had an effect on this virus and they were already familiar with the drug for treating malaria. But now he's changed his mind about it, and last week, Sahlgrenska hospital stopped using this drug for COVID-19. He says that there have been reports of more serious side effects than they initially expected. I don't totally understand what he says next about the dosage ("och det är ett svårdoserat läkemedel" = "and it is a hard-dosed drug"? Maybe it is usually administered at high doses?), but it seems like they can't determine whether it will cause serious side effects, including affecting the heart, and there is no strong evidence that it actually treats COVID-19. They worry about heart problems for seriously ill COVID-19 patients so they are worried klorokin may be harmful to some patients. He doesn't know of any cases of severe side effects in Gothenburg but he's says that there have been reports from other clinics. 

The basis for discontinuing klorokin treatment is that there is a risk of severe side effects and there are no controlled studies showing it helps. Magnus Gisslén alludes to the methodological issues with the French study and says that it offers very little evidenciary value. 

Here they also note that all hospitals in Västra Götaland county have stopped treating with klorokin but says these and Salgrenska are the only hospitals so far. The major hospitals in Sotckholm are still giving klorokin. Dr. Gisslén says he's hearing that other regions are also planning to stop. He says he's very confident in what he's come up with and thinks that's how you should handle it. (Further down they explain that his hospital treats with [IVA](https://www.sodertaljesjukhus.se/for-patienter/mottagningar/intensivvardsavdelningen/vad-ar-iva/) which I believe is a protocol involving putting patients on a respirator but can look into if we want more details, and not with antivirals). He says they should not be doing experimental medicine so that they can be sure they're not doing any harm. The article notes there are lots of clinical trials going on for COVID-19 treatments and he says if they show that klorokin is good then of course they will resume using it. But until then they don't want to risk patients' health by administering it. Below he notes that they might think differently if there were a very high death rate from COVID-19, but right now they're able to manage most of the intensive care cases.

Anna Myrnäs is a consulting physician** in Poison Control who says they have been getting more inquiries about side effects from klorokin, including cardiac arrest. She thinks that not everyone who prescribes it, especially for patients who are already in intensive care, is aware of how serious the side effects can be. 

Gisslén regrets getting drawn into the klorokin-yran (chloroquine acid) now that he knows about the side effect profile and hopes that the rest of the country will also change its mind. 

Södersjukhuset in Stockholm (where Carl Sydenhag was treated) has also stopped for the following combination of reasons: no positive clinical effects have been demonstrated, potential risk for side effects, they're waiting to see what controlled trials in other countries show. 

** Överläkare, I don't know exactly the equivalent in the American system but it means a specialist doctor with management responsibilities in a hospital

**Comment by cbrueffer** [comment]
You've summarized things well, and I can't really add much more to it; if the reports are true it's only a local decision, not a recommendation by the Swedish authorities. The whole thing is quite confusing.

What does seem to be the case is that now generally only specialized doctors (rheumatologists, etc) can actually prescribe (hydroxy)choloquine, although exceptions in the hospital setting (e.g. for COVID-19) are unaffected by this change: https://www.lakemedelsvarlden.se/nu-begransas-forskrivning-av-klorokin-i-sverige/

**Comment by rando2** [comment]
Update: Brazil is now saying the same thing and the US seems to be doing better at translating this time. I'm glad the heart effects are becoming better known!
<https://www.usatoday.com/story/news/2020/04/15/coronavirus-chloroquine-test-halted-drug/2983129001/>
