### ISSUE TITLE
Chatroom for Contributors and Developers

### ISSUE THREAD

**Issue by mprobson** [greenelab/covid19-review#19]
Many open source software projects have a dedicated chatroom to discuss their project, welcome newcomers, and provide rapid feedback. Might be something to consider in this context as well as a place for people to quickly ask questions, get help, and contribute without directly engaging with GitHub.

Some Examples:
- Gitter
- Slack
- MS Teams
- IRC
- Discord

Pros:
- Real time feedback
- Helpful space for novices intimidated by GitHub and worried about making mistakes
- Rapid discussion between all interested parties in a centralized hub as opposed to email, issues, PRs, SMS, Slacks, etc.

Some potential downsides:
- Fractures discussion between several spaces (as opposed to concentrating discussion here)
- Potentially adds yet _another_ service novices must sign up for (Gitter uses Twitter/Github so this wouldn't be a problem)
- Could obscure some conversations that happen in private channels (yet those might already be happening anyway and some projects, i.e. Gitter, are public be default)
- More management overhead for maintainers, e.g. moving messages into issues (I am happy to help with this)

I am happy to elaborate on the pros/cons of each and/or set up the service if that'd be helpful, just let me know!

**Comment by cgreene** [comment]
@mprobson : is this something you'd be willing to lead up? Seeing the interest level in #17 I'm thinking that we'll want a place to at least coordinate folks who can help those who are newer to Git/GitHub. I've used gitter before, and I agree that not having to have a new account is a strength. If you're willing to lead this up, I'll defer to you on what the way to go is :)

**Comment by LucyMcGowan** [comment]
+1 for Gitter

**Comment by mprobson** [comment]
@cgreene Absolutely, I'll work on setting up a Gitter room ASAP. I had a quit chat with some of my colleagues at UIUC and they seem to like Gitter as well.

**Comment by mprobson** [comment]
Looks like someone in the org needs to start the chatroom to link it to this repo, I'll assist @rando2 with this process.

**Comment by mprobson** [comment]
We're live at https://gitter.im/covid19-review/community

**Comment by cgreene** [comment]
I'm there! 👋  Do you want to file a PR to add this to the README.md?

**Comment by mprobson** [comment]
You read me mind! I can also add it to the text if you'd prefer.

**Comment by cgreene** [comment]
What do you think about adding a link to it, the introduce yourself, and the overall repository readme explicitly in the `Abstract` section of the paper? I figure some folks will get here by landing on https://greenelab.github.io/covid19-review/ and won't know to click the "automatically generated from..." part to get to GitHub and contribute.

**Comment by mprobson** [comment]
Seems like a great idea. We could also fence it off in a (new) contribution section(?) between the Abstract and Intro.

**Comment by cgreene** [comment]
Yes! Even better - perhaps "Where to Contribute" with a very short set of pointers? I'm big on DRY but getting folks to the right place is important :)

**Comment by mprobson** [comment]
On it! Also, very glad to hear you're a fan of DRY :)

**Comment by mprobson** [comment]
See #23 , I'm still waiting on CI test to confirm links work.
