### ISSUE TITLE
Enable rolling builds for AppVeyor

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#192]
Our editing workflow involves many reviewer suggestions, which then generate a large number of commits when the pull request author accepts each of them individually.  @cgreene can you please enable [rolling builds](https://www.appveyor.com/docs/build-configuration/#rolling-builds) in AppVeyor to help generate fewer artifact comments?

This feature is only available through the AppVeyor settings, not the configuration file:
![image](https://user-images.githubusercontent.com/3532898/79055550-883ad000-7c13-11ea-9066-85ca8349f835.png)

**Comment by cgreene** [comment]
I just enabled rolling builds for pull requests. Let's see how the next one goes 🤞

**Comment by agitter** [comment]
Thanks @cgreene.  This worked in #174 

![image](https://user-images.githubusercontent.com/3532898/79122237-d60f1f80-7d5c-11ea-87b9-d5af8d315bbc.png)

**Comment by cgreene** [comment]
Yay! 🎉
