### ISSUE TITLE
New Paper (Other): How you can help with COVID-19 modelling

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/covid19-review#222]
Title: Please edit the title to add the name of the paper after the colon.

# General Information
## Please paste a link to the paper or a citation here:

Link: https://doi.org/10.1038/s42254-020-0175-7

## What is the paper's [Manubot-style citation](https://github.com/greenelab/covid19-review/blob/master/USAGE.md#citations)?

Citation: @doi:10.1038/s42254-020-0175-7

### Is this paper primarily relevant to Background or Pathogenesis? 

- [x] Background
- [ ] Pathogenesis
- [ ] Methods

## Please list some keywords (3-10) that help identify the relevance of this paper to COVID-19

* keyword 1 (replace me, copy and paste more than three if needed)
* keyword 2 (replace me, copy and paste more than three if needed)
* keyword 3 (replace me, copy and paste more than three if needed)

## Which areas of expertise are particularly relevant to the paper?

- [ ] virology
- [ ] epidemiology
- [ ] biostatistics
- [ ] immunology
- [ ] pharmacology
- [x] other: general

**Comment by michaelmhoffman** [comment]
This article can help motivate the current review. One of the points of this article is that one of the best ways for scientists who haven't previously worked in a COVID-related area is to, essentially, write reviews like this one! Rather than, say, coming up with your own n00b models.

> Rather than adding noise, amplify the signal. The number of documents appearing on preprint servers is more than anyone can physically read, let alone the additional files being e-mailed and shared around. Perhaps you could contribute to sifting what is out there. For example, when different approaches give different results, you could attempt to identify exactly what is behind the divergence. When you see something particularly useful that has been overlooked, please help by distilling the key message and telling others about it — whether you do so by telling colleagues around you, sharing via social media or other routes. Alternatively, you could work with others to compile summaries and digests of what is out there with respect to some part of the data, models or results.

**Comment by rando2** [comment]
This is great @michaelmhoffman ! If you see anywhere it would fit well in the intro or abstract, please feel free to submit a PR, or otherwise I'll keep it in mind the next time we restructure!

**Comment by ypar** [comment]
This has been addressed in [#PR318](https://github.com/greenelab/covid19-review/pull/318)
