### ISSUE TITLE
New Paper (Other): [The severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) envelope (E) protein harbors a conserved BH3-like motif]

### ISSUE THREAD

**Issue by marouenbg** [greenelab/covid19-review#228]
Title: The severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) envelope (E) protein harbors a conserved BH3-like motif.

# General Information
## Please paste a link to the paper or a citation here:

Link: https://www.biorxiv.org/content/10.1101/2020.04.09.033522v1

## What is the paper's [Manubot-style citation](https://github.com/greenelab/covid19-review/blob/master/USAGE.md#citations)?

Citation: [@doi:10.1101/2020.04.09.033522]

### Is this paper primarily relevant to Background or Pathogenesis? 

- [ ] Background
- [x] Pathogenesis
- [ ] Methods

## Please list some keywords (3-10) that help identify the relevance of this paper to COVID-19

* keyword 1 Protein E
* keyword 2 T cells
* keyword 3 BH3

## Which areas of expertise are particularly relevant to the paper?

- [x] virology
- [ ] epidemiology
- [ ] biostatistics
- [x] immunology
- [ ] pharmacology
- [ ] other:

**Comment by rdvelazquez** [comment]
@marouenbg This paper was actually already summarized here: #195. I'm marking thisas a duplicate and closing this issue. I'll look into why that issue was missed in the script that looks for open issues.
