### ISSUE TITLE
Reorganize Remdesivir Section

### ISSUE THREAD

**Issue by cgreene** [greenelab/covid19-review#294]
**Is your feature request related to a problem? Please describe.**

This section could use a bit of a reorganization.

**Describe the solution you'd like**

Some things in "Summary" probably belong in the header about the drug. The current state of how it's being used in treatment is in the header about the drug. It is probably best to have some elements of those results in current evidence. The bit about the EUA from the FDA should probably be reported in the summary.

**Describe alternatives you've considered**

We could simply add the FDA bits to the "Summary" section, but I think a good look at this subsection can identify additional opportunities for optimization.

**Additional context**

N/A

**Comment by rando2** [comment]
There is also quite a bit of new research that it would be good to add!
