### ISSUE TITLE
Permanent storage of instructions for checking artifacts

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#31]
> @cgreene since we don't have AppVeyor notifications linking directly to artifacts and GitHub Actions comments are still being explored ([manubot/rootstock#322](https://github.com/manubot/rootstock/issues/322)), we should stick your screenshots and instructions above somewhere permanent. They'll be very helpful for pull request reviewers.

Do we have / want a Wiki for this?

_Originally posted by @agitter and @mprobson in https://github.com/greenelab/covid19-review/pull/23#issuecomment-602922827_

**Comment by rando2** [comment]
I agree with this line of thinking. I know @cgreene has successfully done it within a repository in the past, but a wiki might not be a bad idea just because it's a bit more of a familiar format for people across fields. 

We may also want screenshots of exactly how editing a page (e.g., here is the pencil), proposing a branch, and making a PR will look to reduce barrier to entry for new users. I'd probably say we should do this showing how to add yourself to the metadata -- most of the contributors have not done that, so there seems to be some reservation. 

I'm not sure whether we'll need this for issues as well, or if that is similar enough to other media that the barrier to entry isn't as bad.

I'm happy to put together a PR for the intro stuff but wanted to open a discussion about format in line with @agitter & @mprobson 's discussion above.

**Comment by cgreene** [comment]
I have no strong feelings on this, but I agree that having it somewhere would be helpful. I tend to prefer the readme for "broadcast" instructions since it's the first thing folks see when they show up, but if folks are more comfortable with a wiki that's fine too. :)
