### ISSUE TITLE
Questions on Reproduction Number Section

### ISSUE THREAD

**Issue by rdvelazquez** [greenelab/covid19-review#313]
@alavendelm and @johnbarton the [reproduction number section](https://greenelab.github.io/covid19-review/#reproduction-number-and-dynamics-of-transmission) that you wrote was really informative. I just had a couple questions after reading it and thought I'd share in-case they can help improve the document or if others had similar questions:

1. - [x] Do we think it’s worth noting the efforts at “live”predictions of Rt? I know of https://rt.live and https://epiforecasts.io/covid/ but there may be others.
2. - [x] "R0 and Rt can be estimated directly from epidemiological data or inferred using mathematical modeling: the susceptible-infected-recovered (SIR) model and its extensions [39](https://greenelab.github.io/covid19-review/#ref-lwH4gcts).” Is this the right citation for SIR model and extensions? It seemed like that paper was related to just the intra-host response.
3. - [x] Would a tabular or graphical summary be a useful addition? Maybe something like a row for each paper and columns for: location, date range the estimate covers, method used, point estimate, CI range and source/link. Something similar was done here: https://academic.oup.com/jtm/article/27/2/taaa021/5735319 but it might be a good addition in this review paper because it's a living document and could be updated as new data comes out. I could help out with preparing a table or graph summary if that's something that we want. **Edit: This was discussed below and could be a future addition but likely not in the near term**
4. - [x] The difference between R0 and Rt as used here wasn’t very clear to me. I think we are just using the terms that the cited papers used but the distinction seems arbitrary and might cause confusion. The second paragraph lists estimates of R0 but some of the estimates are explicitly for a specific populations at a specific time (which would make them Rt I believe). For example "on a cruise ship where an outbreak occurred, predicted R0=2.28 [46]” It seems like this should be an effective reproduction number (Rt) rather than basic reproduction number (R0).

**Comment by rando2** [comment]
@rdvelazquez for point 3, @ypar has informed me that manubot can actually pull data and automatically update figures! It is on my to-do list to look into for replacing the beginning of the intro where we talk about case/death numbers, but I haven't gotten there yet. If it's something you're interested in, I can move it up in terms of priority!

**Comment by alavendelm** [comment]
Hi @rdvelazquez, thanks these are v helpful comments. Point 3 (incorporating point 1) would be a great addition! We just need to think carefully about what data sources to use for it to make sure we trust their reliability enough. I will look into rt.live and the other source.

For points 2 and 4, I will (in a couple days) get back to the text for edits and PR these tagging you for review.

**Comment by alavendelm** [comment]
Hm I haven't looked into the methods rt.live are using yet but I find this sentence worrisome

> When Rt is below 1.0, the virus will stop spreading.

the virus will stop spreading *if* Rt is maintained below 1.0 indefinitely. This might just be a communication issue though.

**Comment by yemarshall** [comment]
Hello. In parallel, I made a pull request for a few suggested edits/small additions to the Reproduction Number & Transmission Dynamics section. Maybe some of these edits/adds I suggested in the first paragraph clarify R0 & R a bit -- at least they fill in a bit more info.

**Comment by alavendelm** [comment]
Hi @rdvelazquez, on live Rt tracking, epiforecasts.io looks more reliable than rt.live to me (tho ofc subjective). Shall we add a link to one or both of these at the end of the section? Are these best added just as refs, i.e. `@url:`

**Comment by yemarshall** [comment]
I'm not sure, but this may also be related or complementary info, so I'm just mentioning it in case you find it useful (o/w feel free to ignore of course): CDC has listing of different forecast models here https://www.cdc.gov/coronavirus/2019-ncov/covid-data/forecasting-us.html
