### ISSUE TITLE
Update Summary of HCQ/CQ Section

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#320]
@cgreene wrote in #309:
> I read this paper with interest, thinking a lot about this section of our paper. I think it would be worth noting in the summary section that follows as well. It will probably be good to note this near where we say "This uncertainty is important to recognize clinically because HCQ-based treatments can lead to dangerous side effects like prolonged QT interval [@doi:10.1155/2016/4626279]."
> 
> That summary is probably due for a bit of a larger update as well. I also just noticed while reading that section, it looks like there's still a note in there that @rishirajgoel has some content to be added as well. Is that current?

@rishirajgoel @soumitagh @hufengling @nafisajadavji @catherinedawn anyone want to take this on?

**Comment by nafisajadavji** [comment]
I can work on this.

**Comment by dziakj1** [comment]
Maybe the section needs to be changed in light of the recent Lancet retraction?

**Comment by cgreene** [comment]
Yup

**Comment by rando2** [comment]
[There is also evidence it does not work as prophylaxis](https://www.nejm.org/doi/full/10.1056/NEJMoa2016638) -- although I didn't read this study yet, so am not speaking to the strength of this claim
