### ISSUE TITLE
Help: Deploy failing because of file size

### ISSUE THREAD

**Issue by cgreene** [greenelab/covid19-review#342]
## What are you trying to do?

Merge a completed pull request.

## What problem are you running into?

The deploy is failing, it looks like it's possibly because of file size on computed files: https://github.com/greenelab/covid19-review/runs/705763506?check_suite_focus=true

**Comment by agitter** [comment]
Current [GitHub policies](https://help.github.com/en/github/managing-large-files/conditions-for-large-files) are to warn for files > 50 MB and block pushes with files > 100 MB.

```
remote: error: File covid19-lit-all.tsv is 149.56 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: File AllenAI-metadata.csv is 180.90 MB; this exceeds GitHub's file size limit of 100.00 MB        
```

Compressing these two files would be a good first step.

**Comment by agitter** [comment]
I'm working on this in #344

**Comment by agitter** [comment]
The compressed output files are now < 100 MB.  Check the build logs from this run: https://github.com/greenelab/covid19-review/pull/344/checks?check_run_id=707356778#step:7:4733
