### ISSUE TITLE
Expanding the scope to include public health policy / epidemiology

### ISSUE THREAD

**Issue by rdvelazquez** [greenelab/covid19-review#36]
Should this review paper also explicitly address public health policy / epidemiology? Is there a critical mass of folks who can help manage contributions in this area? 

Some specific subtopics that a section like this could address are listed in the comment below.

**Comment by rdvelazquez** [comment]
**Public Health Policy**

Potential topics could include:
- Contact tracing
- Prioritizing testing resources
- Social distancing (effectiveness and  implementation)
- Communication
- Prediction of spread at various geographic and time scales

I don't personally have expertise in this area but I've seen it play a huge role in the response to COVID-19 and find it hard to understand what the research actually says about these topics. If there are others with expertise in this area who would like to contribute... here's your invitation.

**Comment by rando2** [comment]
Hi @rdvelazquez , Thank you for opening this issue for people to discuss ideas! I think some of your proposed topics might be related to an open issue and an open pull request we have right now, #20 and #22 . Feedback would be much appreciated!

**Comment by rdvelazquez** [comment]
Hi @rando2, Thanks for taking a look at this! I missed #20 and #22 when originally looking into this; they both look good! I think the diagnostics section is a good place to discuss practical considerations for testing. If a section eventually gets added regarding public health policy some of that information could be moved at that point if warranted.

**Comment by alavendelm** [comment]
I think a section on population dynamics could be valuable -- overlapping with several of the bullets mentioned by @rdvelazquez above: covers prediction of transmission dynamics (see #69), and potential guidelines/strategies for contact tracing, may also touch upon demographics (though with more complicated models).

**Comment by cgreene** [comment]
@nolankav - just saw your introduction over in #17 and I wonder if you want to join this conversation

**Comment by rdvelazquez** [comment]
FYI - I've narrowed the scope of this issue (changed the tile and intro comment) to help keep things organized. It's now specifically addressing expanding the scope for public health policy / epidemiology rather than any proposed expansion of scope.

**Comment by nolankav** [comment]
There's a potential angle on SES/income how it complicates social distancing (e.g. if you live paycheck-to-paycheck, you're less likely to distance). This could support targeted, cost-effective policies and economic interventions for reducing transmission.

Or are socioeconomic considerations beyond the scope of the paper?

Also worth discussing ethical issues regarding testing and policy interventions. Tracing movements is less socially acceptable in the West than in China, for example.

Can take a look at other angles, too.

**Comment by alavendelm** [comment]
Re: discussion of epidemiology & population dynamics - I'd be happy to draft a section on this. Several modeling works (including #69 and #109) provide useful estimates of R_0, R_t, and the effects of social distancing. 

it seems that this can either belong to its own section of fit within `Pathogenesis.md` under the heading "Viral Replication, Spreading and Transmission" or elsewhere? Ok to start by drafting this within the Pathogenesis section, and move later if better?

**Comment by rando2** [comment]
Hi @alavendelm , that sounds great to me! Thank you so much for taking the lead on this! It shouldn't be too hard to move it later if we decide it fits better somewhere else.

**Comment by rdvelazquez** [comment]
## Quick update on level of interest:

**Four people have expressed interest or suggested related papers:** @alavendelm, @nolankav, @rando2, @cbrueffer 

**Five paper's have been suggested / summarized:**
#69 - Early dynamics of transmission and control of COVID-19: a mathematical modeling study
#103 - Substantial undocumented infection facilitates the rapid dissemination of novel coronavirus (SARS-CoV2)
#104 - Aerosol and Surface Stability of SARS-CoV-2 as Compared with SARS-CoV-1
#109 - Potential roles of social distancing in mitigating the spread of coronavirus disease 2019 (COVID-19) in South Korea
#114 - Impact of non-pharmaceutical interventions (NPIs) to reduce COVID-19 mortality and healthcare demand

Seems like the current approach is to include these areas in background or pathogenesis and then move to their own section later if needed, which makes sense to me. 

I'll let the maintainers and contributors take it from here but I'm more than happy to help with organization / administrative things and will keep an eye on this issue in the next few weeks.

**Comment by alavendelm** [comment]
Thanks @rdvelazquez. I am working on a section on transmission for the background, covering #69, #103, and #109. 

Here not covering #104 and #114 -- these probably fit best elsewhere.

**Comment by rdvelazquez** [comment]
Closing this now. There is a section on reproduction number and some of these other items were touched on in the intro.
