### ISSUE TITLE
Improve styling of JHU CSSE global deaths figure

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#389]
The first version of the JHU CSSE global deaths figure in the introduction uses default styling (#382).  Someone familiar with Python matplotlib or seaborn could edit the code that generates this figure to make it more appealing.

The code to edit is on the `external-resources` branch:
https://github.com/greenelab/covid19-review/blob/5cb25aa45a2a223a4b0b061e14fa75212dd75098/csse/generate-csse-stats.py#L35-L39

**Comment by rdvelazquez** [comment]
@agitter how about this as a slight improvement?

**New**
<img width="568" alt="Screen Shot 2020-06-25 at 9 56 01 AM" src="https://user-images.githubusercontent.com/25244432/85733357-1f1f1080-b6ca-11ea-84bf-8d037d6338f2.png">

**Original**
<img width="578" alt="Screen Shot 2020-06-25 at 9 57 31 AM" src="https://user-images.githubusercontent.com/25244432/85733576-4d045500-b6ca-11ea-86ea-4cf360d8247b.png">

**Comment by rando2** [comment]
I don't think I've adequately expressed my enthusiasm for how cool this figure is!!!!!

**Comment by agitter** [comment]
@rdvelazquez that's definitely an improvement.  Should we make the line a little thicker as well?

**Comment by rdvelazquez** [comment]
Good idea with the thicker line:
<img width="554" alt="Screen Shot 2020-06-25 at 11 58 01 AM" src="https://user-images.githubusercontent.com/25244432/85754784-5ba73800-b6db-11ea-848f-8dc911c760d5.png">

**Comment by agitter** [comment]
Closed by #405 and #427
