### ISSUE TITLE
Duplicate entries in appendix

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#432]
While doing some spell-checking, I found that there is at least one duplication in the appendix -- 8.25 and 8.119 are identical. I am making this issue as a reminder to look upstream to see whether it's duplicated there, and to come up with a programmatic way to check for other duplicates.

**Comment by agitter** [comment]
To help our investigation later, the title of the duplicate review is "Breadth of concomitant immune responses underpinning viral clearance and patient recovery in a non-severe case of COVID-19".

I glanced at the latest review markdown files and noticed there are some preprints with a review and another "alt" review.  The filename patterns are also less standardized.  We should probably update the appendix and push corrections upstream once more before submitting this manuscript.

**Comment by agitter** [comment]
#561 reports additional duplicate entries.

**Comment by rando2** [comment]
I believe there are quite a lot, but I haven't done a systematic analysis yet! @cgreene might have some initial ideas about what could be happening. They don't appear to be two authors creating reviews of a single paper, but rather the same review getting added twice (we catch them because of typos typically).

**Comment by agitter** [comment]
@rando2 @cgreene I believe I corrected this in #564
