### ISSUE TITLE
Suggestions for Topics from @aadattoli

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#44]
Here I upload a document with several points of discussion, including the most recent literature on the most hopeful experimental drugs (I have found 4 of them), as well as diagnostic tests, based on antibody detection, recently developed. I also added some thoughts concerning the Italian Covid-19 situation.

Please let me know your feedback.

Best,

Ada
[20200326_Corona virus review.pdf](https://github.com/greenelab/covid19-review/files/4376923/20200326_Corona.virus.review.pdf)

_Originally posted by @aadattoli in https://github.com/greenelab/covid19-review/issues/17#issuecomment-603413314_

**Comment by rando2** [comment]
Hi @aadattoli , I hope it is OK that I pulled this out to be a new thread so that people can give you feedback. I did a first read of your document and will think about the best places to incorporate each section in, if that sounds good to you!

**Comment by nilswellhausen** [comment]
I think some aspects of 1 can be nicely incorporated into the pathogenesis section (immune response and disease mechanism) and then reiterated in the therapeutics sections of course.

**Comment by aadattoli** [comment]
Hi all, I just wanted to say that I can go deeper into the mechanism of action of each drug. 

Plus, looking at numbers, women seem to be less susceptible to Corona virus virulence compared to men. In fact, on a sample of 44600 cases in china as per Feb 11 2020, male deaths in men was about 65% higher than women (men=2.8%; women=1.7%). The trend in Italy is similar, women represents 28% of the deaths and in South Korea men accounted for 62% of the cases. Something makes women stronger than men for this type of virus. There are several hypothesis about it, but this might be crucial in the economic recovery of the countries affected, as women could for instance get back to work prior to men, being less sensitive to the virus. 
I am not sure whether this fits the topic of the review. Let me know if you guys are interested.

**Comment by rando2** [comment]
Hi @aadattoli  this looks great! I think you might be interested in #54 as well. 
Do you want help suggesting these papers? You can talk with some of us live by going to:
https://gitter.im/covid19-review/community
