### ISSUE TITLE
Add correlation analysis to methods

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#513]
@bansalvi conducted an analysis of two RNA-Seq analyses in #347. We need to make sure we integrate this into the methods and also report the statistics in line with journal requirements.

https://github.com/bansalvi/COVID19-Greene-Cor/blob/master/Cor_TenOverLandthaler.R

**Comment by agitter** [comment]
@rando2 I edited your original post to fix the link

**Comment by rando2** [comment]
Superseded by #612
