### ISSUE TITLE
Expanding the CRISPR-based detection section?

### ISSUE THREAD

**Issue by SystemsResearch** [greenelab/covid19-review#520]
I was wondering if there was any interest in updating/expanding the section on CRISPR-based detection (section 3.1.3.1 in my build). At the moment, it only covers the Zhang paper and the Chiu preprint.
The Chiu paper is now published, and there have been other studies since then.
Or is too niche and therefore fine as it is?

**Comment by rando2** [comment]
@SystemsResearch It would be wonderful if you want to work on/expand that section!

**Comment by SystemsResearch** [comment]
Great!
I should be able to get to it over the next couple of weeks.
