### ISSUE TITLE
Public versus Academic Balance

### ISSUE THREAD

**Issue by rhagenson** [greenelab/covid19-review#53]
**Is your feature request related to a problem? Please describe.**
Given how rapidly information is being disseminated on general public-facing platforms and this pandemic being a global community concern, I think this review should have some aspects of general public-facing information. Reading through the albeit limited discussion thus far, I do not think such public-facing elements are in the plan.

**Describe the solution you'd like**
The review certainly cannot be pulled out of academic and toward losing the nuance of the issues at hand so I propose a "checkpointing" solution for any public or media-crew readers. I foresee this being sort of "bottom line" elements in highlighted boxes (supported in Manubot?), as well as asides for addressing any public misinformation. We cannot allow this review to be pulled so far toward obscure academic hair splitting that such a publicly accessible resource which will evolve as we learn more is impenetrable to a non-academic reader.

**Describe alternatives you've considered**
Mentioned above I see the solution as highlighted boxes in the manuscript, but could also foresee a section of public questions with brief answers starting the review. For example:

+ Is hydroxychloroquine a miracle cure for coronavirus (1)? No (2), there have been some preliminary studies (3), but...(4)

This is intentionally structured as a clear question (1), clear answer (2), why the question is on peoples' minds (3), then what the literature tells us as academics (4).

I would not consider a separate document as there is not way to ensure the two are consistent and current. One document with public and academic elements is the solution, in my opinion. How these elements are presented and laid out on the page is the concern.

**Additional context**
My motivation for this feature request is that this review will be easily accessible to all and can be leveraged to combat misinformation if only we allow room for doing so.

**Comment by sjspielman** [comment]
I think it is very important to recognize that the general public needs clear, unambiguous guidelines that do NOT require them to be meandering through citations or references. The overall structure of a manuscript is similarly very overwhelming, and most lay people will take a quick glance, conclude "this looks complicated and science-y", and move on. The format and content of manubot papers are excellent for academically-oriented audiences, but very difficult and intimidating for non-academics. It is an admirable goal to have a single reference point for everyone, but the psychology of getting non-scientists to even skim through a scientific-looking document and absorb anything seems impossible. 

A way to keep a single document functioning to this end is to have separate sections: 1) Q/A for "lay people" written in clear and non-technical terms. 2) The meaty manuscript section where the scientists will go. This would have to go beyond sections of a manuscript - again, non-scientists won't give the webpage half a second if it looks "too smart for them."

**Comment by rando2** [comment]
Part of our goal in doing this in this way is to provide a hub for the media to check hype against. Your suggestion is interesting -- I'm imaging something similar to pull-out boxes that you'd see in a textbook?  

Would you be interested in helping draft "TLDR"s as we move along?

I think your suggestion could be possible format-wise with manubot, but I'm not one of the manubot experts on the project. Let's check in with them (e.g., @dhimmel , @agitter )

**Comment by rhagenson** [comment]
@sjspielman It sounds like you are in support of the alternative I suggested then? A quick Q/A to start the manuscript so any public looking see that first, then the standard review article format below it. If moving in that direction, I still think a visual distinction should be made by highlighting the Q/A portion in some way (even subtlety so).

However, I disagree with you on non-scientists rejecting to read further if it is "too smart for them" so propose internal hyperlinks for where the answers in the Q/A are discussed at greater depth in the body of the review. We need to lead people to answers if they want them.

**Comment by rhagenson** [comment]
@rando2 I certainly will help build the TLDRs. Once we have a majority (or as close as we can) vote on if we want this in the review and how it looks I am willing to push for these public-facing elements at each turn.

**Comment by rhagenson** [comment]
Oh, forgot to respond to the "pull-out boxes" question. I think the visual and interactive nature of this will depend on what Manubot can do now, or be made to do readily. I leave that up to the Manubot experts as, although I have followed the project for months, I do not know it extensively enough to engineer a best solution.

**Comment by sjspielman** [comment]
@rhagenson, I'm not interested in arguing about what non-experts will or will not read, but I caution that we need a solid grasp of the psychology. Most people are deeply stressed and not able to focus on websites that are overly-complex, and for a non-academic, websites STRUCTURED as manuscripts are viewed as overly-complex - even regular newspaper articles are (sadly) overly complex for many people out there used to only taking in news from social media posts. I do not have immediate answers here, but pull-out boxes and TLDRs will be nice to have at a minimum. Some thought should go into how those look visually - make them loud and compelling for clicking.

**Comment by rando2** [comment]
It's definitely an interesting idea -- I am envisioning it might be possible to do something like in journals where the editor gives a bit of an overview of what the paper does/shows/why it matters, although I think this might still be complex because we'd probably have to do it for each section.     @sjspielman (also, hi, it's been quite a while!) it's great to have you here because you have so much experience with science communication! 

We do want to try to keep pace with what the general public is hearing and try to make sure we're addressing the hot topics (e.g., chloroquinine). I'm not sure how this will play out long-term because as scientists, I imagine for quite a while, our understanding will be "there's _some_ evidence for XX as a therapeutic but..." 

Emily Oster (economist at Brown), for example, very effectively communicates pros and cons of risk for the general public, but that's definitely a particular skill set that I at least don't have experience with.

**Comment by dhimmel** [comment]
> I foresee this being sort of "bottom line" elements in highlighted boxes (supported in Manubot?), as well as asides for addressing any public misinformation

Since Manubot supports HTML, we can likely support any type of formatting you'd like... perhaps some styles more easily than others. @vincerubinetti is our frontend expert and can assess the feasibility of specific formats if you ask.

One example of something similar is in https://greenelab.github.io/scihub-manuscript-es/, which is a translation where the original untranslated text is expandable:

> ![image](https://user-images.githubusercontent.com/1117703/77549210-f21e5000-6e85-11ea-874f-3a6fc445f563.png)

It sounds like you might want boxes that are not collapsible or start out collapsed.

You can start marking sections with special formatting before we have the actual CSS style implemented using [pandoc's `fenced_divs` syntax](https://pandoc.org/MANUAL.html#divs-and-spans) like:

```
::: {.tldr .boxed}
Here is a paragraph.

And another.
:::
```

Since the `tldr` and `boxed` classes aren't defined yet, nothing will render differently until we define them.

**Comment by rando2** [comment]
Thanks @dhimmel ! That's great to know. I'll keep you and @vincerubinetti in the loop as things move forward.

**Comment by vincerubinetti** [comment]
> It sounds like you might want boxes that are not collapsible or start out collapsed.

Wouldn't boxes that are not collapsible just be the same as the banners we already have?

As for collapsibles, we should probably build that into Manubot anyway. It seems like a common enough request. I can do that right away, if people need it.

Also it might help to get rid of all the manubot formatting stuff in the latter half of the manuscript. It threw me off when I first saw it, and it's probably good to keep things as lean and on-topic as possible, given the circumstances.

**Comment by dhimmel** [comment]
> Wouldn't boxes that are not collapsible just be the same as the banners we already have?

Ah good point. In that case, the following could be sufficient:

```
::: {.banner .lightblue}
Here is a paragraph.

And another.
:::
```

@vincerubinetti Is it better to use a div or span for multiple paragraphs here?

**Comment by vincerubinetti** [comment]
A div would be more appropriate, but both should probably work just fine.

Divs are "block" elements and spans are "inline" elements. Think of a div as a paragraph: takes up the full width of a line, and multiple divs usually go on top of one another vertically. Think of span as a few words within a sentence you want to style differently than the rest: it goes in line with the regular flow of text.

**Comment by rhagenson** [comment]
@sjspielman I apologize if you felt I was arguing, that was not my intention. My statement was intended to ensure the Q/A does not become disconnected from the rest of the review via proposing internal hyperlinks to where the details are within the body of the review for those confident enough in their skills to seek further details.This review should certainly move as a meritocracy and I am not a science communication expert. It sounds like you are far more experienced in this regard so if you are willing to work with me on building this Q/A content, I am willing to learn from you.

@rando2 I certainly expect most of the questions will start out as little more than "we do not know yet" but where we cannot give answers we can give pause for what is still developing. I see some value in that even if it is not the definitive answers that people want.

**Comment by agitter** [comment]
If the goal is to have TLDR section that is accessible to the general public, a highlighted box seems like a good format.  That is essentially what Molecular Systems Biology does with its Synopsis section (e.g., https://doi.org/10.15252/msb.20188664).  Many other journals have this as well but without the colored background.

**Comment by rhagenson** [comment]
@agitter That is pretty spot on for what I am envisioning now, but with internal links to more details rather than standalone synopsis. The internal links are intended to solve two problems: 1) allow public to move toward details in the body, and 2) ease onboarding of new collaborators when/if we reach a point where our collective expertise is not enough.

**Comment by rando2** [comment]
This seems like a great topic to revisit since there is interest in its utility and it seems like promise on the tech side as well! I think we might want to circle back to this in a little bit once we have a bit more substance put together in the text, before we sent @vincerubinetti off to try to implement it, but this is a great discussion we should definitely keep in mind as we move forward!

**Comment by RLordan** [comment]
I definitely like the idea of a public element to this! Really great idea considering everybody academic and non-academic is attempting to follow the news and indeed the literature to try learn more. An editorial from a journal or something like that could certainly act as a platform. Is it worth considering other avenues such as a supplementary file with a lay-version breakdown. That is unorthodox, but what is normal these days!

**Comment by cgreene** [comment]
I think this is a really important discussion, and I'm glad it's occurring. We don't yet have the scientific content for the paper in place with extensive review of the rapidly developing literature, so I think it may be a bit early to expect that we could produce a version for the public that would be appropriately communicative and grounded in evidence.

For now, I'd propose that we add a banner that says this is by scientists and intended for scientists. That it should not be considered to provide treatment guidance of any sort. Then we can link out to resources that are more appropriate at this time.

I'd propose the CDC website and https://covid-101.org/, both of which appear to be better suited than this review. How does that sound? I'll file a PR so we can see what it would look like.

**Comment by rhagenson** [comment]
@cgreene That sounds reasonable to me.

**Comment by cgreene** [comment]
I filed #76. Would love to get feedback on it.

**Comment by RLordan** [comment]
@cgreene Good idea, that's fair.
