### ISSUE TITLE
Update affiliation for @yemarshall

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#541]
I don't know the least messy way to edit the file again (don't want to mess up the PR that was already approved), so asking you to add if you want affiliations (although not required, but just for regularity with other names) / you can put the following two affiliations/notes (without department because I had 2 programs funding me and the PhD part is done):
affiliations:
  - freelance copyeditor
  - recent PhD, Princeton University

_Originally posted by @yemarshall in https://github.com/greenelab/covid19-review/pull/395#discussion_r460581172_

**Comment by yemarshall** [comment]
this reminder isn't needed anymore, I made a PR #546
