### ISSUE TITLE
Make sure everyone's funding is up to date

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#596]
@cgreene mentioned that before we submit, we'll need to make sure all of the funders are up-to-date (and probably reconfirm COI too).

**Comment by agitter** [comment]
I need to submit an update.  I'll aim to do it this week.

**Comment by scapone01** [comment]
No funding, no COIs.  Thanks all!

**Comment by SiminaB** [comment]
Same for me!

**Comment by dziakj1** [comment]
I don't have any funding or COI's for this project.

**Comment by RLordan** [comment]
No COI's either, thank you all.

**Comment by cgreene** [comment]
I added @scapone01 @SiminaB @dziakj1 and @RLordan's updated dates in #598
