### ISSUE TITLE
Grouping Therapeutics into Categories

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#61]
There have been some exciting new suggestions for avenues we can explore in the section on therapeutics! (Thanks, @rlordan and @nilswellhausen !) 

Initially we had just thought about:

1.  Symptom management, probably largely via pharmaceuticals
2. Antivirals
3. Vaccines

But now we have content about nutraceuticals and clonal antibodies as well. 

Does anyone have ideas about how to most effectively group these into categories? Is there a hierarchical structure at all, where some of them are more or less similar to others, or do we have 5 distinct categories as the text reflects now?

**Comment by cgreene** [comment]
Nutraceuticals feel to me like they would be likely to fall into 1 or 2.

Antibodies... (or, for that matter, serum/plasma from recovered patients) I'm not so sure. Maybe 2? Maybe their own group?

**Comment by rando2** [comment]
Excellent! Once we have a few categories we feel good about, I might number them to try to help make the flow easier to see. We have so many categories that the header demarcations aren't as helpful as they were when the outline was a bit more barebones!

**Comment by nilswellhausen** [comment]
I thought about that already too! Neutralizing antibodies can be somewhat antiviral as they block proteins that are important for eg. viral entry. However, vaccines work by inducing an immune response in which neutralizing antibodies are generated. I tried to find if they can be classified as one or the other but did not find any stringent rule for that.

**Comment by cgreene** [comment]
Maybe we should handle antibodies / serum / plasma as their own category. I agree with @nilswellhausen that it's not clear.

**Comment by RLordan** [comment]
I'm not sure if nutraceuticals should get a mention as a seperate category or they should be intermingled to the pre-existing categories. I think a separate section might be appropriate as some do work as antivirals, but others are thought to increase the activity of the immune system, which is a separate mechanism. The other thing to consider is the negative impact of nutraceuticals and whether or not they even work! There is significant criticism in the literature surrounding vit C and D etc and the use of various elderberry and zinc extracts. This could be something to capture if nutraceuticals was a separate section. Anyone else have thoughts on that. I can provide literature.

**Comment by agitter** [comment]
> The other thing to consider is the negative impact of nutraceuticals and whether or not they even work!

This is far outside my expertise, but this line caught my eye.  If we do include nutraceuticals, let's be sure to be objective and thoughtful about the published and pre-printed work if there are concerns about their efficacy.

**Comment by Jeff-Field** [comment]
We should have subcategories of Therapuetics.
Antivirals:
1 viral protein targeted drugs (eg protease, polymerase, anti-spike antibodies)
2 Host protein targeted drugs (eg. Ace2)
3 Non-targeted drugs (eg. hydroxychloroquine)

**Comment by RLordan** [comment]
@agitter  I am currently writing a bit on this and it will be critical but very fair to the nutraceutical literature. I will be happy for others to appraise and contribute. The thing about nutraceuticals is that the FDA is hazy about their use generally, but people believe in 'natural' products. Take one look at the supplement sections in shops last week and any elderberry, zinc, and vit C supplements were sold out. I think the efficacy and potential mechanisms of nutraceuticals is an important discussion to have for sure.

**Comment by nilswellhausen** [comment]
I was thinking about a structure for this section and I would like to hear your opinion on this:

What if we separate broadly into small molecule drugs and biologicals?

Small Molecule drugs:
1. Viral protein targeted drugs (nucleoside analogs, protease inhibitors, s protein targeted drugs)
2. Host protein targeted drugs (ACE2 etc)
3. Non-targeted drugs (This includes nutraceuticals and Hydroxychloroquine)

Biologics
1. Antibodies (Neutralizing Antibodies as well as things like IL-6 blocking antibodies like tocillizumab)
2. Vaccines (DNA, (m)RNA, Protein, Virus Particles)

**Comment by rando2** [comment]
@nilswellhausen I really like your suggestion -- this reads very intuitively to me! What do others think?

**Comment by RLordan** [comment]
I'm on board with that, it makes sense

**Comment by nilswellhausen** [comment]
I have my issues with the word "non-targeted" though as every drug has some sort of target. Is there a more suitable name you can think of for the drugs that do not target virus or virus related host structures directly?

**Comment by RLordan** [comment]
I was going to suggest non-specific but that also has connotations to it... miscellaneous or something to that effect?

**Comment by cgreene** [comment]
Does polypharmacological drugs work for those? Granted everything has some amount of polypharmacology to it (especially at high concentrations).

**Comment by RLordan** [comment]
True, that might work actually

**Comment by nilswellhausen** [comment]
Yeah that or Broad-spectrum pharmaceuticals

**Comment by nilswellhausen** [comment]
I created a PR with the changes in structure

**Comment by rando2** [comment]
@RLordan would you be able to give @nilswellhausen feedback on #95 ? I'm putting together a tutorial on how to give in-line feedback like the trivial suggestion I left, I will let you both know as soon as I have it ready!

**Comment by SiminaB** [comment]
I missed this discussion and had written up some notes regarding classification of therapies. Does this makes sense? https://www.evernote.com/l/AZWKg3dA9tNO-Jg-sp2zKRgrIOZYDbWQOu4/

So for instance, broad-spectrum pharmaceuticals are all used for treatment and symptom reduction, not as antivirals, correct? (since they have a more systemic vs targeted mechanism)

**Comment by nilswellhausen** [comment]
I think one way or the other is fine. I personally don't like the broad distinction between targeting the host vs the virus because of the overlap. For example, nucleoside analogs are considered antivirals for a good reason but they obviously target host proteins. Antibodies can target the virus envelope directly or you can have antibodies like tocilizumab that block the IL6R systemically to reduce symptoms. There is so much uncertainty about how these drugs actually work in the context of COVID-19 that I think it is really difficult to classify drugs based on their mode of action but rather on their basic properties (Biologicals vs Small Molecule).

**Comment by SiminaB** [comment]
Got it @nilswellhausen! I agree that mechanism can be especially hard. I'll take a stab at a PR with some changes tonight or tomorrow.

**Comment by SiminaB** [comment]
Should we have vaccines under "therapeutics" or in a separate section?

**Comment by RLordan** [comment]
> I think one way or the other is fine. I personally don't like the broad distinction between targeting the host vs the virus because of the overlap. For example, nucleoside analogs are considered antivirals for a good reason but they obviously target host proteins. Antibodies can target the virus envelope directly or you can have antibodies like tocilizumab that block the IL6R systemically to reduce symptoms. There is so much uncertainty about how these drugs actually work in the context of COVID-19 that I think it is really difficult to classify drugs based on their mode of action but rather on their basic properties (Biologicals vs Small Molecule).

I agree with that summation @nilswellhausen, there is a lot yet to be determined for these therapeutics. Indeed, one aspect of all this that has not been considered much is the pleiotropic effects that might be observed from various therapeutics in the setting of COVID infection. I think mode of action is probably too specific at this stage? Anyone else want to chime in?

**Comment by RLordan** [comment]
> Should we have vaccines under "therapeutics" or in a separate section?

That's a good question, what do you think @rando2 @nilswellhausen ? Technically a therapeutic vaccine is administered after infection. Should the overall section be called 'Therapeutics and Pharmaceuticals' or 'Prophylactics and Therapeutics' .... because some of the nutraceuticals may also work prophylactically rather than therapeutically.

**Comment by rando2** [comment]
@RLordan, I agree, it does seem like we are also discussing prophylactics and might want to re-evaluate the header! There does seem to be quite a bit of conflation of the two ideas in the popular press (e.g., people taking HCQ as a prophylactic) so it would probably be wise to define which treatments might be prophylactic! If we changed the heading, do you think we would we need to do any additional reorganization?

**Comment by SiminaB** [comment]
So change the header to "Therapeutics and Prophylactics?" I can include that in the PR I'm working on.

**Comment by RLordan** [comment]
> @RLordan, I agree, it does seem like we are also discussing prophylactics and might want to re-evaluate the header! There does seem to be quite a bit of conflation of the two ideas in the popular press (e.g., people taking HCQ as a prophylactic) so it would probably be wise to define which treatments might be prophylactic! If we changed the heading, do you think we would we need to do any additional reorganization?

Hey @rando2 , I don't think we would need to change any of the subheadings after that. The text accompanying the potential treatments seems to identify the therapeutics from the prophylactics on its own.

**Comment by SiminaB** [comment]
I was gonna make some small subheading changes based on the classification I had above.

**Comment by rando2** [comment]
@SiminaB that sounds good to me!

**Comment by SiminaB** [comment]
For the drug classes, did we decide we can put broad-spectrum pharmaceuticals such as HCQ and CQ and neutraceuticals under "small molecules?"

**Comment by SiminaB** [comment]
I guess my classification was the same as @nilswellhausen's... Gotta work on my reading comprehension  :) But right now the headings are a bit different from that. I will incorporate some of the discussion here as well into the text.

**Comment by SiminaB** [comment]
Can someone explain the difference between monoclonal antibodies (mAbs) and neutralizing antibodies (nAbs)? Is one a subset of the other?

**Comment by nilswellhausen** [comment]
Neutralizing antibodies are often not monoclonal but rather polyclonal. As the name suggests, they neutralize their target by binding to a structure that prevents that the target can bind to its natural ligand. Monoclonal antibodies can have functions beyond neutralizing. They are both a subset of antibodies but I wouldn't say that one is a subset of the other and vice versa.

**Comment by SiminaB** [comment]
Thank you! I won't have a separate category for each in that case.

**Comment by SiminaB** [comment]
The "neutralizing antibodies" subsection right now seems to confuse nAbs and mAbs a bit. I may also not be reading it properly since I'm not an immunologist or virologist.

**Comment by SiminaB** [comment]
Alright, just made the PR. I ended up changing some of the subsections (Anticipated Mechanism, Current Evidence, Summary) to just bold font at the beginning of the paragraph, as we were running out of subsections in some cases :-) (and to keep consistency.) @rando2 and others - let me know if this doesn't make sense. We may also consider numbering some of the subsections for the purpose of making it easier to keep track of things.

**Comment by rando2** [comment]
@SiminaB, we looked at numbering but it was too much to try to maintain. However, numbers are now automatically generated for the manuscript itself! (#207)
