### ISSUE TITLE
Subpopulations of Special Concern Revision

### ISSUE THREAD

**Issue by cgreene** [greenelab/covid19-review#610]
**Is your feature request related to a problem? Please describe.**

I think this section could use a significant revision.

**Describe the solution you'd like**

Here's what I wrote in the TODO I added to the manuscript:
> I think this section could use a revisiting. I think we should deal with the male sex and older age portion in an initial paragraph. After that, it looks like the racial burdens are likely to be attributable in large part to systemic racism - incarceration, wage discrimination, housing discrimination, and more - both now and in the past. Right now this jumps around b/w groups and presents discrimination as the basis in disparities as a possibility but not necessarily a likely contributor. I also worry that it makes many of these things research questions, even though one of the resources we cite ( 10.1093/tbm/ibaa055 ) includes policy recommendations. In short, it feels like we list a bunch of proximal causes but don't tie things back to the overarching likely cause. Finally, the way genetic factors are brought up makes me worry that someone might have, as a takeaway, that genetics may play a driving role in disparities at this level. 

**Describe alternatives you've considered**

We could restructure this in a number of ways. What's here right now feels to me like it wanders around the point more than addressing it.

**Additional context**

**Comment by dziakj1** [comment]
I guess that reorganization would make sense.  I know that @rando2  is working with a student on a related section in the discussion.  When we are discussing research issues, there is another interesting paper we should mention:
Griffith, G., Morris, T. M., Tudball, M. et al. (2020). Collider bias undermines our understanding of COVID-19 disease risk and severity Epidemiology. @doi:10.1101/2020.05.04.20090506

**Comment by dziakj1** [comment]
The equity section in the discussion is discussed in #552 -- I don't know how to determine which information goes in each of the two sections, though.  @tlukan and @rando2 are working on it.

**Comment by dziakj1** [comment]
Also, another important paper just came out on probability of mortality conditional on hospitalization (@doi:doi:10.1001/jamanetworkopen.2020.18039)
with commentary (doi:10.1001/jamanetworkopen.2020.18696)
https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2769387
https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2769381
I haven't read it yet, but apparently the racial disparities appear more in the probability of getting infected and/or hospitalized, not the probability of death conditional on hospitalization.

**Comment by rando2** [comment]
@dziakj1 I have a draft PR in the works and will tag you when I put it up! Thanks for the articles!
