### ISSUE TITLE
Figure showing structure of the genome

### ISSUE THREAD

**Issue by cgreene** [greenelab/covid19-review#614]
**Is your feature request related to a problem? Please describe.**

There was a TODO for a figure showing the structure of the genome that predates my edit, though I did put it into a `TODO:` comment upon revision.

**Describe the solution you'd like**

I guess a figure showing the viral genome would be included. 😁 

**Describe alternatives you've considered**

Not having a figure, which is probably ok too, though I will say from reading it that a figure would probably help.

**Additional context**

**Comment by lubianat** [comment]
Would be an option remake/reuse a CC-BY figure with proper captions? 
the wikimedia one is good, but CC-BY-SA which might be a barrier for some cases. 
https://en.wikipedia.org/wiki/Severe_acute_respiratory_syndrome_coronavirus_2#/media/File:SARS-CoV-2_genome.svg
