### ISSUE TITLE
Method TODO: Flesh out CI strategy in methods

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#621]
**Is your feature request related to a problem? Please describe.**
@agitter is planning to update the methods, but @cgreene mentioned in #619 that it would especially great to mention the branch-based output strategy so that future projects know it's an option!

**Describe the solution you'd like**
Just making an explicit issue for what I believe is already on Tony's to do list: it would be great if he could look through the methods and provide a bit more insight 

**Describe alternatives you've considered**
I took a shot in #619 but it's not as detailed as would be ideal

**Additional context**

**Comment by agitter** [comment]
Thanks for the reminder and issue.  I'll wait until #619 is merged and then add any updates on top of that draft.  Thanks for taking on the bulk of the writing for the Methods.

**Comment by rando2** [comment]
Supersedes #570
