### ISSUE TITLE
Figures for first submission

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#673]
Are all the figures we intended to include in the first version of the manuscript in place?  I haven't been keeping up with all the recent pull requests so I may have missed discussion about this.  However, I noticed several really nice figures that aren't included:
- https://github.com/greenelab/covid19-review/blob/external-resources/ebmdatalab/ebmdatalab-map.png
- https://github.com/greenelab/covid19-review/blob/master/content/images/N001-LifeCyclePlusDrugs.png
- https://github.com/greenelab/covid19-review/blob/master/content/images/N002-Vaccines.png

**Comment by rando2** [comment]
I'll open a PR right now! I meant to add these in during the restructure and it fell off my radar.

**Comment by agitter** [comment]
Closed by #600 and #688
