### ISSUE TITLE
Add paper review templates as appendices

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#712]
**Is your feature request related to a problem? Please describe.**
In the methods, we mention the issue templates for reviewing papers. These need to be added as appendices.

**Describe the solution you'd like**
Need to copy the text into new content for the manuscript.

**Describe alternatives you've considered**

**Additional context**
Thanks to @agitter for catching this in #698

**Comment by agitter** [comment]
@rando2 I can work on this
