### ISSUE TITLE
Project-Wide Submission Status

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#731]
Hi COVID-19 Lit Review collaborators!
Last week we began speaking to an editor about submitting to _mSystems_, and they asked for a word count -- it turns out the main text of the manuscript has grown to 45,000 words! Because of the issues this would present for peer review, they suggested that we split the text into ~5 distinct subsections of approximately 10,000 words, each of which we can continue to update as "living" documents (per the original intent of this project!)

I ran this by our Gitter chat, and people there seemed enthusiastic. Personally I think there are a number of advantages to this approach (not least of which is actually being able to find reviewers!), especially since one of the motivations for this project was providing an avenue for wet lab grad students who weren't able to access the lab to continue publishing during 2020.

Right now, intuitive sections seem to be (shoutout to @nilswellhausen, @RLordan and @cgreene for helpful feedback here):
1. Pathogenesis & Transmission (documents 07.pathogenesis.md & 08.transmission.md)
2. Diagnostic technologies (document 10.diagnostics.md)
3. Pharmaceutical Prophylactics & Therapeutics (part of section 20.therapeutics.md)
4. Nutraceutical Prophylactics & Therapeutics (part of section 20.therapeutics.md)
5. Social factors influencing COVID-19's spread/prognosis (most of 50.discussion.md)
6. Application of an open publishing framework to an emerging public health crisis (edited version of 60.methods.md)

We would most likely divide the introduction and parts of the discussion up among the sections.

@davidmanheim raised the concern that updating 5-6 documents might be a little challenging, so there is a conversation going on about the best way to manage this. One option would be to keep everything in this repository and have separate pdfs/html documents compiled for each section. Another would be to create multiple repositories. (Shoutout to @lubianat and @agitter).

For authorship, @cgreene and I discussed the idea of having certain named authors based on the commit history (thanks to the magic of git & Manubot!) and then everyone's names in a box as members of this consortium. This would also make the burden of approval/review a little lighter on each individual author, since you wouldn't have to approve sections you don't have a background in!

I would love to hear your thoughts! Apologies that the submission process has turned out to be a little tricky, but it's really incredible how much content we have here! 45,000 words is a small book.

**Comment by cgreene** [comment]
Hmm - interesting question about whether to keep one document here and make the output a presentation issue vs keep 6 documents and then merge into one for someone who wants "everything". I think I like the idea that the living hub document that then gets split out (though we should probably rearrange the .md files to make each one a paper), but this is off the cuff.

**Comment by agitter** [comment]
The proposed division of content into manuscripts looks good.  If anyone else is curious (like I was), the approximate word counts are:
```
$ wc -w *.md
   323 00.front-matter.md
   265 01.abstract.md
  2950 02.introduction.md
  6198 07.pathogenesis.md
  5079 08.transmission.md
  3957 10.diagnostics.md
 20342 20.treatments.md
  6484 50.discussion.md
  1336 60.methods.md
   149 70.coi-contribs.md
    21 90.back-matter.md
    19 94-ismms-appendix-header.md
 42112 95-ismms-himc-appendix.md
  2809 96-template-appendix.md
 92044 total
```

If paper 6 ("Application of an open publishing framework...") is an overview paper, it could also include much of the intro and brief new text summarizing the others (~1-2 paragraphs each).

@cgreene do you want to maintain one merged version of everything?  If the 45k word version is too long for reviewers, it may be too much for most readers as well.  My initial thought was to make the GitHub Pages version as similar as possible to the intended journal version but keep the source content structured as is.

For authorship, you may also want to consider contributors who played a significant role in pull request review even if they didn't commit content to that section.  Or do the co-authored commits generated when reviewers leave suggestions take care of that?

**Comment by RLordan** [comment]
Just on another note, I assume because of the restructuring and the formation of essentially 5-6 papers there will probably be additional workload non-code related. This includes sections like introductions, abstracts and some sort of concluding remarks etc. that will either be reformulated from existing text or written up from scratch. I am happy to help with any of those to move the project along. @rando2 @cgreene et al. don't get snowed under with the extra workload, feel free to reach out and thank you all for organizing.

**Comment by marouenbg** [comment]
I think this is an excellent opportunity. Thanks @rando2 for your leadership on this, let me know how can I help.

**Comment by rando2** [comment]
Thank you so much everyone for the feedback! @RLordan and @marouenbg, I will definitely keep you in mind for help with moving text around (which I'm planning to start opening PRs for starting Monday, since we have a holiday in the US tomorrow and Friday).

I'm planning to open a second issue to address the technical side of this so we can hopefully get some feedback from some of the other Manubot developers!

Best wishes,
Halie

**Comment by rando2** [comment]
Status update:
| Section | Title | Status Issue | Submission Goal |
| -- | -- | -- | -- |
| Pathogenesis/Transmission | Genomic and Viral Structure of SARS-CoV-2 in the Context of Pathogenesis, Symptomology, and Transmission | #744 | January 22 |
| Nutraceuticals | Dietary Supplements and Nutraceuticals Under Investigation for COVID-19 Prevention and Treatment | #749 | January 29 |
| Pharmaceuticals | Identification and Development of Prophylactics and Therapeutics for COVID-19 | #738 | February 5 |
| Diagnostics | TBD | N/A | TBD |
| Evolution | TBD | N/A | TBD |
| Discussion (Social Factors) | TBD | N/A | TBD |
| Methods (Cyberinfrastructure) | TBD | N/A | TBD |

**Comment by rando2** [comment]
I'm going to propose closing this issue and moving the status updates to the README, per a suggestion from @agitter on Twitter!
