### ISSUE TITLE
Steps for Nutraceuticals Manuscript Submission

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#749]
1. Abstract to be added
2. Add a section of misinformation/caution 
    - This section is labeled misinformation for now, but basically just before the conclusions section it is important we highlight and caution the lack of regulation surrounding these products, lack of safety and efficacy data, and misinformation peddled for financial gain.
3. Update Vitamin D 
   - massive strides in research here indicating that patients tend to be vitamin D deficient and there have been two small trials indicating therapeutic benefits when vitamin D is administered early in the disease course.
4. Update Introduction
    - update info on sales of nutraceuticals and why this topic is relevant to COVID-19
5. Zinc 
   - some data for zinc in combination with hydroxychloroquine and Azithromycin has been published
6. Conclusions 
   - tidy up required.

Adapted from #748 by @RLordan

**Comment by rando2** [comment]
OK, from looking through the commit history for the old combined therapeutics section and the new nutraceuticals section, I actually think there is an EXTREMELY short author list for this section because @RLordan did so much of the heavy lifting!

1. @RLordan
2. @rando2 
3. Consortium author
4. @agitter & @cgreene (I'm not sure how you're allocating last-authorship across the project!)

I can post my approximates of contributions if people want, but since it's so short, it seems fairly clear cut. @RLordan if you have a memory of anyone contributing that I'm missing, please let me know! Christian did fix a couple of typos, but as far as I can tell, he's the only other person who touched this text.

I think @RLordan is planning a few more edits/additions, but I have given the bulk of my comments already in #814 and #815 (and I'm happy to do a final copy-editing sweep prior to submission for whitespace/abbreviations/missing words/etc-- assuming @RLordan won't mind!) @RLordan does submitting Monday sound realistic to you?

I guess the other next step is for me to update the metadata, assuming this all sounds good! And @RLordan, perhaps you have some ideas on people we could request as reviewers? There are also a [few editors](https://msystems.asm.org/content/board-editors) with interests in nutrition and metagenomics, so I assume one of them would be best to request?

**Comment by agitter** [comment]
I think I should just be included in the consortium author for the nutraceuticals manuscript and don't need to be listed as an individual author.  I wasn't involved in this particular manuscript and don't know the scientific area well enough to understand and approve everything.

The parts I have read through look very thorough and polished.  Great work @RLordan and @rando2!

**Comment by RLordan** [comment]
Hey Folks, great to see it come together. The only other person I think who might have contributed was @hufengling but maybe I am getting that confused with sections from the therapeutics paper? Maybe they can let us know? Monday sounds realistic, I might get some time tonight to update the citations. If not, I will definitely have it done by Saturday evening. I would be delighted if @rando2 can do a final sweep of the manuscript before submission. I can certainly suggest some reviewers to you. Will I email them to @rando2 ? have you got a penn email still?

**Comment by rando2** [comment]
Awesome! @RLordan I still have my Penn email, and I can loop Casey in as well if you don't have his email (since he's the one who does the actual submitting!) I just approved #817 and I'll merge in #815 and #817 tomorrow morning -- and then we can get a word doc generated!

**Comment by RLordan** [comment]
> Awesome! @RLordan I still have my Penn email, and I can loop Casey in as well if you don't have his email (since he's the one who does the actual submitting!) I just approved #817 and I'll merge in #815 and #817 tomorrow morning -- and then we can get a word doc generated!
> 
> @agitter I will probably tag you for every paper because I feel like you've solved problems related to almost every line of this document 😆 -- but I definitely agree, this one was like 98% Ronan!

Perfect will email you guys a list of potential reviewers shortly

**Comment by rando2** [comment]
Manually changed the acknowledgements to: We thank Vincent Rubinetti and Daniel Himmelstein for feedback on and support with Manubot and Yael Evelyn Marshall for feedback on pieces of the text.
