### ISSUE TITLE
Steps for Diagnostics Submission

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#818]
1. Add title & abstract
2. Update sustained immunity #770 ✅ 
3. Update CRISPR  #866 
4. Check ddPCR vs dPCR spelling
5. Check other terminology issues (described in #869)
4. Update author list
5. Confirm text with authors
6. Final check of text

**Comment by rando2** [comment]
As an update, the authorship based on current content is below. However, there is definitely quite a bit of work to do here (see #852), so I didn't go through the commits carefully, as I expect the order could definitely change based on what happens in the next week! I just wanted to ping the authors so we can try to come up with a plan for what should happen. Ideally we'll get this manuscript into reasonable shape this week so we can submit it around February 19-22.

Est Position | Username | Line changes as of Feb 10
-- | -- | --
1 | @rando2| 614 + intro/discussion text
2 | @cbrueffer  | 187
3 | @davidmanheim  | 169
4 | @aadattoli  | 158
5 | @SystemsResearch  | 46
6 | @davemai  | 23
6 | @LSH2126  | 19
7 | @SiminaB  | 11
8 | @agitter | non-text but lots of project admin/software components
9 | @cgreene | 44

Ack to: Lucy McGowan and Greg Szeto

There are lots of suggestions in #852 for things that could happen to strengthen this paper, so please feel free to discuss those here or propose your own!

**Comment by SystemsResearch** [comment]
I have had a go at the CRISPR update (see pull request just above).
Hopefully this is not coming too late.

**Comment by rando2** [comment]
I believe these are all handled now, either previously or in #1091. Moving this submission PR to #1094
