### ISSUE TITLE
Submit Pathogenesis build to arXiv

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#821]
@agitter suggested that we might want to post our submitted build as a preprint somewhere. I think this is an awesome idea, not least because it will make it easier to reference this paper as we submit the remaining manuscripts!

@cgreene has volunteered to do the first one and I should be able to do later ones (I don't have anything on arXiv yet so don't have posting privileges).

**Comment by cgreene** [comment]
I am trying to figure out my arXiv login information 😢

**Comment by RLordan** [comment]
> I am trying to figure out my arXiv login information 😢

**Comment by RLordan** [comment]
I meant to comment 'awesome', instead I closed the issue and had to reopen it. Nobody trust me with anything important :(

**Comment by agitter** [comment]
What arXiv subject area will you use?  I'm guessing q-bio, and I can endorse for q-bio.MN (and have my password 😆).  If @rando2 submits to arXiv, I can endorse her if it's required.

**Comment by cgreene** [comment]
I recovered it! Here we go 🚀

**Comment by cgreene** [comment]
This one is now submitted!

**Comment by cgreene** [comment]
Your article is currently scheduled to be announced at Tue, 2 Feb 2021 01:00:00 GMT.
Updates before Mon, 1 Feb 2021 19:00:00 GMT will
not delay announcement.

**Comment by agitter** [comment]
Closed by https://arxiv.org/abs/2102.01521 !
