### ISSUE TITLE
Broken DOI in Evolution

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#833]
Hey @RLordan,
@cgreene caught that one of the dois we added in #816 does not seem to exist on the internet! Do you have any guess what @doi:10.1101/2020.12.05.2024192 was supposed to refer to?

`This deletion has also been associated with several RBD mutations [@doi:10.1101/2020.11.19.389916; @doi:10.1101/2020.12.05.2024192; @url:https://virological.org/t/preliminary-genomic-characterisation-of-an-emergent-sars-cov-2-lineage-in-the-uk-defined-by-a-novel-set-of-spike-mutations/563].`

I'm sorry I didn't catch this when it was fresher in everyone's mind!

**Comment by RLordan** [comment]
Hey @rando2 @cgreene Apologies. It took some head scratching, but I believe it is this one: https://doi.org/10.1101/2020.12.14.422555

Recurrent emergence and transmission of a SARS-CoV-2 Spike deletion H69/V70

**Comment by rando2** [comment]
Thank you so much @RLordan!
