### ISSUE TITLE
Two authors left off pathogenesis manuscript 🤦‍♀️ 

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#849]
**Is your feature request related to a problem? Please describe.**

I inadvertently left the two of the authors involved in generating the visualization off the pathogenesis author list -- @kevinsunofficial and @qiyanjun. I just caught it because I added them to the therapeutics manuscript and noticed this credit was missing.

**Describe the solution you'd like**

We need to add them in when we get to the revision stage. I'll open a PR to fix their credit after #848 merges.

**Describe alternatives you've considered**

I have a better way to handle this now, I was still figuring out an approach for assigning credit on that first manuscript and clearly hadn't worked out all the bugs yet.

**Additional context**
@cgreene just wanted to let you know about this mistake!

#744 
See also #813 for fixes needed at re-submission

**Comment by cgreene** [comment]
We should re-submit to arXiv with the full author list too, since the review and revision stage may take some time.
