### ISSUE TITLE
Revisions for Pathogenesis Manuscript

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#892]
Here are the first round reviews from the Pathogenesis Manuscript as an itemized list and the full text:
- [x] Reviewer 1.1
- [ ] Reviewer 1.2
- [ ] Reviewer 1.3
- [ ] Reviewer 1.4
- [ ] Reviewer 1.5
- [x] Reviewer 2.1
- [x] Reviewer 2.2
- [ ] Reviewer 2.3
- [x] Reviewer 2.4
- [ ] Reviewer 2.5
- [x] Reviewer 2.6
- [ ] Reviewer 2.7
- [ ] Reviewer 2.8
- [ ] Reviewer 2.9
- [x] Reviewer 2.10
- [ ] Reviewer 2.11
- [x] Reviewer 2.12
- [ ] Reviewer 3.1
- [ ] Reviewer 3.2
- [ ] Reviewer 3.3
- [ ] Reviewer 3.4
- [ ] Reviewer 3.5
- [ ] Fix author metadata #813 #849

## Reviewer 1
Rando et al., provide a thoughtful and comprehensive review of the scientific literature relevant to the COVID-19 pandemic. This review will provide a useful resource for the scientific community but is missing some crucial information and would be improved by a more clear description of how this virus is detected and the limitations of these methods. 

Major:
**1.1** Heparin sulfate dependency: The 'Pathogenic mechanisms' section is lacking any reference to the dependence of SARS-Cov-2 binding to heparin sulfate which has been cited over 100 times since its publication in November and has been supported by work from numerous labs:
https://www.sciencedirect.com/science/article/abs/pii/S0092867420312307

**1.2** Furin discussion: The description of furin in this manuscript is confusing; it is highlighted in the conclusion as a mutation that has allowed for increased virulence, but is not mentioned in the opening paragraphs of the paper where host proteases are described (e.g. lines 229-235, line 279), or the section describing the hinge-like movement of the spike protein which is induced by furin (lines 591-603) and only mentioned fleetingly in the middle of a the next paragraph. A more thorough discussion of the furin-site insertion in the SARS-CoV-2 genome (and what information is still missing) earlier or more prominently in the paper is warranted.

**1.3** Detected versus infectious: The distinction between RT-qPCR detection and viral infection assays in cell culture models should be more clear. Although this point is acknowledged (e.g. lines 713-714) it is not clear whether viral RNA or infectious virus is being described at certain points in the review (i.e. line 663) and a brief description of the advantages and limitations of these methods would be useful for the reader.

Minor:
**1.4** Typos
- Lines 205; The legend of Figure 1 incorrectly states that RNA polymerase is a protease
- Line 709; typo -> 'either typical or atypical'
- Line 755; 'content level' should be 'continental level'?
- Line 788; what does adding the 'exposed' variable in this model mean and why is that important for SARS-CoV-2
- Line 852; typo, duplicate 'has coordinated'
- Line 874; typo, "as in the current pandemic"

**1.5** This work is important not only for the current moment, but for contextualizing this virus for response to future outbreaks; in my opinion it would be nice to have a sentence in the discussion to this effect (this review represents a ton of work - the effort is worthwhile!)

## Reviewer 2
Overall, this was a very comprehensive, thorough review of the current state of knowledge of SARS-CoV2. The manuscript is well written and extensively researched, with great attention to the details of the outbreak with regards to data from various regions of the world, providing an extremely useful resource for the scientific community. The manuscript is well researched and well written for a general scientific audience. I only had a handful of minor concerns, mostly for word choice/organization for clarity but I would leave these changes at the discretion of the authors as they do not detract from the overall narrative of the manuscript. 

Minor Points

**2.1** Line 196 - insert "the" prior to replication. 

**2.2** Lines 213-214 - wording was a bit odd, might suggest adding "a process conserved among coronaviruses" to the previous sentence. 

**2.3** Line 250-252 - might suggest excluding skin and just keeping mucus, the way this reads suggests the respiratory mucosa provides no protection at all- is this true? 

**2.4** Line 275 - suggest changing "can facilitate" to "may facilitate"

**2.5** Line 311 - reference was not highlighted in blue- not sure if this was a formatting issue but may want to check to make sure this reference is correct. 

**2.6** Might suggest moving up the Pediatric Presentation (Lines 428-454) to immediately before cytokine release syndrome as it follows the clinical presentation and directly leads into the cytokine release syndrome. 

**2.7** The intro paragraph for the cytokine release syndrome is quite long and could be readily shortened (or even eliminated) without sacrificing the relevant information pertaining to COVID-19 (which is primarily the second 2 paragraphs). 

**2.8** Might suggest moving the cytokine section to be under the Systems-Level Effects rather than Clinical Presentation section, but it could fit in either. 

**2.9** Line 505 - statement regarding other respiratory viruses encoding antagonists to IFN response should reference the relevant studies. 

**2.10** Line 513 - word choice- replace extent with magnitude. 

**2.11** Lines 557-559 - this was a really intriguing statement- can the authors provide an additional sentence or two to provide additional context to why this might be the case?

**2.12** I understand that this field moves ridiculously fast, but in the transmission section it might be worth including the most recent variants that are predicted to have increased transmission.

## Reviewer 3
Overall, the manuscript by Rando et al seeks to review and condense the current corpus of knowledge for SARS-CoV-2. The authors do a great job of making the findings of various studies easy to understand. Overall, this reviewer believes that it will be an excellent resource to the scientific community. This reviewer recommends that the author incorporates a handful of suggested changes (below) to improve the already impressive state of this manuscript.

**3.1** Structure of Coronaviruses, paragraph 1: Please modify the definition of “non-segmented”. It refers more to the fact that it is a single molecule of ssRNA, than to whether it is contained in a capsid.

**3.2** Cytokine release syndrome, paragraph 1: Please modify the wording from “dysregulated systemic inflammation can cause sepsis…” to something similar to “dysregulated systemic inflammation can contribute to pathogenesis associated with sepsis”. The reviewer is unsure about the relevance of this sentence since sepsis is associated with bacterial infection rather than viral infection.

**3.3** Cytokine release syndrome, paragraph 2: The relevance of sepsis to this paragraph is also unclear, unless the authors are comparing SARS-CoV-2 infection to other respiratory diseases caused by bacteria. Specifying the relevance of this comparison would be helpful.

**3.4** Molecular signatures and transmission: It may be helpful to the readers if the authors included a brief synopsis of viral comparative genomics analyses that have been performed including:
- https://www.sciencedirect.com/science/article/abs/pii/S0140673620317578
- https://www.sciencedirect.com/science/article/pii/S0092867421000805
- https://jvi.asm.org/content/94/17/e00790-20.abstract
- https://www.sciencedirect.com/science/article/pii/S0092867420304864

**3.5** Conclusions, paragraph 3: The same reference (222) is included twice for the same statement.

**Comment by agitter** [comment]
@rando2 it looks like the authorship issues #813 and #849 have already been fixed.  Is that correct?

**Comment by rando2** [comment]
@agitter I believe all of the ones that can be fixed here are fixed in #879 and #850. Marouen's last name needs to be fixed in mSystems portal.
