### ISSUE TITLE
Revisions for Pharmaceuticals Manuscript

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#899]
Here are the first round reviews from the Pharmaceuticals Manuscript as an itemized list and the full text:

- [x] Reviewer 1.1
- [x] Reviewer 1.2
- [x] Reviewer 1.3
- [x] Reviewer 1.4
- [ ] Reviewer 1.5
- [ ] Reviewer 1.6
- [x] Reviewer 1.7

## Reviewer 1

This review article is an excerpt from a comprehensive COVID-19 encyclopedia available online at https://greenelab.github.io/covid19-review/. The section on therapeutics has been submitted, which is a topic of broad interest. The strengths of this review are its scope and detail, including many useful citations. However, multiple major weaknesses were noted:

**1.1** Lack of conceptual organization. The review is organized by type of drug. While I could see the value in this as a resource it does not translate well to a review article that can be read in one sitting. What is the intended audience of this piece? If it is clinicians, it may make more sense to organize the sections based on how promising the therapeutic is. If it is basic scientists, it would help to group the interventions by mechanism of action or some other biological question. 

**1.2** Too much text discussing failed approaches and limitations of clinical trials. A considerable amount of text is spent on chloroquine, despite the wide consensus that it does not have an effect. In contrast, promising approaches like monoclonal antibodies are given just a few short paragraphs. I also felt that the in-depth criticisms of clinical trial design were unnecessary and distracted from the main message of each section. They are certainly valid points, but it would be great to get the conclusion across in a more concise manner, while providing references that enable interested readers to dive deeper into each study's strengths and weaknesses. It also seems dangerous to infer researcher biases like p-hacking without more definitive data that support these potentially damaging claims.

**1.3** This article as presented seems premature. I was especially confused by the statement in the abstract that "this review will be updated as progress is made." Is that even possible at mSystems? More importantly, the conclusion for all but 1-2 therapeutics is that more data is needed, leaving me wondering what the value of this review is at time present. One useful contribution would be to rank the promise of each approach. Each has issues, but which ones are worth investing more resources in? 

Minor points: 

**1.4** Figure 1 - I'm not sure this adds much to the current topic.

**1.5** Figure 2 - panel labels (letters) are needed. The y-axis of panel 4 is difficult to read - the panel should either be stretched or some of the less common approaches could be trimmed off. The "other" category could also be removed. More importantly, I worry that this figure is immediately out of date, is there any indication that these trends will be stable over time? If not, why is it important to know what fraction of trials are in Phase 2 right now?

**1.6** Figure 3 - I really liked this figure and would like to see it earlier in the review. One concern I have is that all of the drugs are equivalent on this diagram, which could lead the reader to think that HCQ/CQ are effective. Perhaps it would be safer to remove the drug names and indicate the various mechanisms that could be theoretically targeted. Or alternatively, the thickness of the arrows could be used to indicate current data on efficacy.

**1.7** typo on Line 1288 - "reduce accelerate"

**Comment by agitter** [comment]
Addressing the major comments will require a fairly substantial organization.  The suggestion to consider the audience is well taken and would be a good starting point.

One benefit of preprinting v1 of this manuscript on arXiv is that the detailed version is available and archived.  We can consider converting this into a more condensed and readable synopsis for the revision.

**Comment by cgreene** [comment]
One thing that I thought about was potentially taking what's there and more or less treating it as an appendix, and then the paper becomes the review of the review. 😁

**Comment by athril** [comment]
This resource may be helpful in reviewing the drugs for the manuscripts @agitter @cgreene:
https://pharmaceutical-journal.com/article/feature/everything-you-need-to-know-about-the-covid-19-therapy-trials

**Comment by rando2** [comment]
To do:
- [ ] Figure out how to split up/reference appendix (one big appendix? sections for each drug or drug class?)
- [ ] Tweak Fig 1 (#962)
- [ ] Add computational screening text (#961)
- [ ] Add abstract
- [ ] Minor additions/edits: dexa usage since last summer, add description of biological (e.g., virological) research in HCoV since 2000, clean up mabs conclusions, clean up discussion

**Comment by rando2** [comment]
@nilswellhausen for the reviewer's point 1.6 (the cool figure showing all the mechanisms of action), do you have any thoughts? Currently (in #965) I have left the figure in the same spot in the discussion, but we could definitely move it up. However, it sounds like they wanted some visual tweaks-- I'm curious what you think!
