### ISSUE TITLE
Section on treatment with hydroxychloroquine

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#92]
Would anyone be willing to do some research on the support / questions surrounding treatment with hydroxychloroquine? @rishirajgoel had mentioned that we don't seem to have anyone looking at it yet, and obviously it's a very popular topic right now.

If you find any interesting papers and can record them (with the DOI and some background info) as a [New Paper (Therapeutic)](https://github.com/greenelab/covid19-review/issues/new/choose) in the Issues, that would be great! Even better if you want to start to fill out the questions in the Template describing what the studies do/find.

Additionally, it would be great to start putting together a rough draft or an outline for that section of the [treatments](https://github.com/greenelab/covid19-review/blob/master/content/20.treatments.md) analysis, if anyone is interested.

@cgreene found this resource that might be helpful: http://www.uphs.upenn.edu/antibiotics/COVID19.html

Please use this space to discuss and collaborate!

**Comment by nafisajadavji** [comment]
I can help with this. I have added one paper. I will add more information tomorrow. Time for some zzz's.

**Comment by rbharath** [comment]
I'm glad to help with this too. Derek Lowe's [recent blog post](https://blogs.sciencemag.org/pipeline/archives/2020/03/24/the-latest-coronavirus-clinical-trials) has some commentary on this [report](http://subject.med.wanfangdata.com.cn/UpLoad/Files/202003/43f8625d4dc74e42bbcf24795de1c77c.pdf) from China with more chloroquine experimental data. The abstract is in English, but the bulk of the paper is in Chinese so I'm not sure if it's a good ref to cite.

**Comment by hufengling** [comment]
I added information to the issue started by @nafisajadavji

**Comment by hufengling** [comment]
I've been looking into this subject and would love to help work on a draft for a hydroxychloroquine section for the Treatments section. I feel comfortable commenting on clinical data, but would like a second pair of eyes for on comments regarding pre-clinical/mechanistic data. I'm happy to draft something up for both and submit a pull request (perhaps by end-of-day?)

**Comment by rishirajgoel** [comment]
> I've been looking into this subject and would love to help work on a draft for a hydroxychloroquine section for the Treatments section. I feel comfortable commenting on clinical data, but would like a second pair of eyes for on comments regarding pre-clinical/mechanistic data. I'm happy to draft something up for both and submit a pull request (perhaps by end-of-day?)

Happy to give it a second look @hufengling . I have a decent amount of experience with HCQ (at least in the rheum setting) and am familiar w/ a lot of the preclinical studies.

**Comment by nafisajadavji** [comment]
> I've been looking into this subject and would love to help work on a draft for a hydroxychloroquine section for the Treatments section. I feel comfortable commenting on clinical data, but would like a second pair of eyes for on comments regarding pre-clinical/mechanistic data. I'm happy to draft something up for both and submit a pull request (perhaps by end-of-day?)

Do you think we should review a few more papers before we write the section? I have one on my list, it's an in vitro paper. 

If you feel comfortable writing the section, please do go ahead. I will continue to review papers and add them. I will also contribute to the text.

**Comment by hufengling** [comment]
Yes, I think it is important to keep on reviewing papers. I'm planning on looking at a few more today and uploading them with comments, but I think (at least for clinical studies) we've looked at enough to draft a section to add to later.

**Comment by hufengling** [comment]
Hi everyone! I just submitted a pull request with a draft on hydroxychloroquine as a therapeutic. I'd love to have comments/edits, no matter how small!

**Comment by rando2** [comment]
I put up a summary of what's going on in Sweden over at #160 in case it's useful to you all!

**Comment by soumitagh** [comment]
I everyone, I submitted a pull request with a draft on hydroxychloroquine. Please let me know the edits.

**Comment by nafisajadavji** [comment]
I made some suggestions. I think some more details might help clarify the information.

I also added an in vitro study to the pull request, please let me know what you all think.

**Comment by soumitagh** [comment]
Hi @nafisajadavji  and @rando2 : I made the changes as suggested. I have a query, 
My status shows "closed pull request". Please let me know if I did something wrong. Should I open a new pull request?

**Comment by soumitagh** [comment]
Hi @rando2  and @nafisajadavji , I made the changes suggested reviewer

**Comment by soumitagh** [comment]
Hi everyone, I submitted a pull request with a draft on hydroxychloroquine. Please let me know the edits.

**Comment by nafisajadavji** [comment]
Thanks for the ping @soumitagh
