### ISSUE TITLE
Manual References for Therapeutics (Pharmaceuticals)

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#981]
Reference information is not rendering for the following citations:
- https://www.fda.gov/media/138946/download
- https://www.fda.gov/media/150319/download
- https://www.fda.gov/media/145801/download
- https://www.phe.gov/emergency/events/COVID19/investigation-MCM/Bamlanivimab-etesevimab/Pages/bamlanivimab-etesevimab-distribution-pause.aspx
- https://www.contractpharma.com/contents/view_breaking-news/2020-08-31/fda-clears-spis-ebselen-for-phase-ii-covid-19-trials

@agitter, apologies that I haven't caught onto this by now, but when you add the manual references, are you manually inserting metadata in the json file? I'm happy to add these but just want to make sure I follow the correct procedure!

**Comment by agitter** [comment]
Yes, I manually create new entries in `manual-references.json` for the URL references that don't return any useful information with Manubot.  I usually copy an existing entry as a template and then fill in whatever information I have for the new URL.

**Comment by agitter** [comment]
I'll fix these in #993.  I found a couple others as well during my proofreading.

What is wrong with https://www.contractpharma.com/contents/view_breaking-news/2020-08-31/fda-clears-spis-ebselen-for-phase-ii-covid-19-trials ?  The current reference looks okay to me
![image](https://user-images.githubusercontent.com/3532898/129299319-fd77e5f4-4536-4372-ab12-3686b4f70a91.png)
